### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by iwasrobbed** [iwasrobbed/Down#10]

**Comment by vincentlong889** [comment]
+1

**Comment by iwasrobbed** [comment]
Resolved by @azeff in https://github.com/iwasrobbed/Down/pull/11 🎉 

Swift 2.3 and below peoples can continue to use v2.0

**Comment by ahanriat** [comment]
It doesn't look like v0.3 has been published on CocoaPods 🙄
