### ISSUE TITLE
[Down] Rendering to attributed string is really slow, requires main thread

### ISSUE THREAD

**Issue by lilyball** [iwasrobbed/Down#100]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

`Down`'s implementation of `.toAttributredString()` invokes `NSAttributedString(htmlString:)`. This is problematic because it's *really* slow, and it also is only safe to do so on the main thread (under the hood this ends up WebKit to do the rendering).

Failing to render on main thread will result in a crash like in #116 

Instead, Down should convert to AST and walk the AST, building up an attributed string directly. This approach would be much faster and would also be safe to run from a background thread.

**Comment by iwasrobbed** [comment]
Thanks for the issue, @kballard 👍 

Indeed, that support was originally added to bridge the gap at the time, since many folks needed `NSAttributedString` support. I personally don't use that feature, but I'm open to others helping to improve upon it with a pull request

**Comment by kengruven** [comment]
It looks like #81 was aiming to do this -- and now it's at [wireapp/Down]( https://github.com/wireapp/Down).

I haven't looked at it or even tried it, so I have no idea if it's complete, or how well it works.

**Comment by iwasrobbed** [comment]
@johnxnguyen has graciously offered to make a PR for their changes in #81 (after a little cleanup) and I would appreciate your review on that once it's ready @lilyball 🙏

**Comment by mglass** [comment]
@johnxnguyen @iwasrobbed Can I help with this somehow? I'd love to be able to close the issues in my app that are related to this 🙂

**Comment by johnxnguyen** [comment]
Hey @mglass , sorry I have been quite busy at work, but I have the day off today so I'll try to get as much done as I can by the end of the weekend. I'll let you know of course if I need some help 😄

**Comment by mglass** [comment]
@johnxnguyen I have a fork in place at https://github.com/mglass/Down that merges your branch with the current master, but I am flailing around somewhat blindly with it. Maybe it'll help as a reference point?

**Comment by johnxnguyen** [comment]
@mglass a quick update: I'm re-implementing what I've done for Wire but with some tweaks to make it more flexible. The Wire implementation is quite specific and instead I want to make it simpler for the library user to be able to control how the attributed string is rendered. The idea is use a visitor pattern and a styler protocol. This protocol contains a style method for each markdown element and each method is invoked by a visitor class.

I'm working directly from the Down repo on a feature branch, I'll push up my current progress tonight after work and create a draft PR for you to check it out. Then we can move any discussions off this thread 😄

**Comment by johnxnguyen** [comment]
@mglass feel free to have a look https://github.com/iwasrobbed/Down/pull/132. We should probably move the discussion to the PR.

**Comment by iwasrobbed** [comment]
FYI: this has been further improved with a default `Styler` via https://github.com/iwasrobbed/Down/pull/177
