### ISSUE TITLE
DownView font size on iPad is huge

### ISSUE THREAD

**Issue by garyhooper** [iwasrobbed/Down#102]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report
I'm using DownView to display an .md file. On iPhone, it appears as expected. On iPad (in landscape mode), the font is huge...approx. 55 characters per line.

## What did you do?

```
let string = try? String( contentsOf: URL( fileURLWithPath: filepath ) ),
let downView = try? DownView( frame: self.view.bounds, markdownString: string, didLoadSuccessfully: { } )
```

## What did you expect to happen?

Reasonable font size on iPad as well as iPhone.

## What happened instead?

Reasonable on iPhone, huge on iPad.

**Comment by iwasrobbed** [comment]
Feel free to customize the CSS to your heart's delight: https://github.com/iwasrobbed/Down/blob/master/Tests/DownViewTests.swift#L74
