### ISSUE TITLE
Blockquote does not work in NSAttributedString

### ISSUE THREAD

**Issue by jdisho** [iwasrobbed/Down#106]
Hello 👋, 

I am having an issue with `blockquote` (>), which does not render when I use `NSAttributedString`

Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

```swift
private let markdownString = """
    The quote

    > Somewhere, something incredible is waiting to be known

    has been ascribed to Carl Sagan.
    """

let down = Down(markdownString: markdownString)
let attrString = try! down.toAttributedString()

textView.attributedText = attrString
```

## What did you expect to happen?

I expect to see something like this: 

<img width="457" alt="screenshot 2018-09-22 at 15 26 00" src="https://user-images.githubusercontent.com/8223362/45917710-e8282500-be7b-11e8-83ff-84c925493ddf.png">

## What happened instead?

However, I see this: 

<img width="457" alt="screenshot 2018-09-22 at 15 26 12" src="https://user-images.githubusercontent.com/8223362/45917714-f6764100-be7b-11e8-9925-b93d4bea8993.png">

**Comment by iwasrobbed** [comment]
This has been fixed on the latest master; I'll push a new CocoaPods update today

<img width="350" alt="screen shot 2018-11-10 at 11 57 30 am" src="https://user-images.githubusercontent.com/317671/48303978-de1bbd80-e4df-11e8-9429-5bb00fd4a9ff.png">

**Comment by iwasrobbed** [comment]
FYI, you can customize this more using the new AST API: https://github.com/iwasrobbed/Down/pull/132

**Comment by iwasrobbed** [comment]
FYI: this is further possible via the default `Styler` via https://github.com/iwasrobbed/Down/pull/177
