### ISSUE TITLE
[DownView] Doesn't reflow text on orientation change

### ISSUE THREAD

**Issue by phoney** [iwasrobbed/Down#111]
Please help prevent duplicate issues before submitting a new one:

* [X ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I have a simple markdown string that I'm displaying using Down on iOS. When I rotate the device the text doesn't reflow. The line breaks don't change. The text just gets bigger in landscape.

I think maybe this is controlled by a meta tag in the html but I'm not sure how to change that.

## What did you expect to happen?

I expect the text to reflow.

## What happened instead?

Portrait and Landscape Screenshots. Notice the line breaks don't change and the font is larger in Landscape.

Portrait
<img width="604" alt="screen shot 2018-11-08 at 11 23 29 am" src="https://user-images.githubusercontent.com/3106038/48212077-dd9cee80-e348-11e8-8f38-20778cbccb9e.png">

Landscape
<img width="817" alt="screen shot 2018-11-08 at 11 23 12 am" src="https://user-images.githubusercontent.com/3106038/48212109-eab9dd80-e348-11e8-93dd-e64bdb1cc384.png">

Below is the markdown (or the first part of it). It's generated automatically by Cocoapods from the licenses of the pods I'm using. Github displays it using formatting.

# Acknowledgements
This application makes use of the following third party libraries:

## Alamofire

Copyright (c) 2014-2018 Alamofire Software Foundation (http://alamofire.org/)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**Comment by iwasrobbed** [comment]
Thanks for filing an issue, @phoney! If this is the case:

>I think maybe this is controlled by a meta tag in the html but I'm not sure how to change that.

then you can change the HTML in the bundle to test it: https://github.com/iwasrobbed/Down/blob/master/Resources/DownView.bundle/index.html

**Comment by phoney** [comment]
@iwasrobbed   I made a PR to address this issue. Setting the meta viewport tag to width=device-width makes the DownView reflow the text on iOS when rotating the device. I think this is the default that most users would want.

**Comment by iwasrobbed** [comment]
Closed in #127 by @phoney 👍 👍 🎉
