### ISSUE TITLE
2 Swift Compiler Errors when installing Down on iOS

### ISSUE THREAD

**Issue by ghowen** [iwasrobbed/Down#117]
* [X ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report
After installing Down via Cocoapods, I get 2 compile errors and cannot build my project anymore 
(Xcode 10.1, Swift 4.2, Target iOS 11).

```
Down Group
Swift Compiler Error Group
/Users/georg/Projekte/Apps/anyfinder/Pods/gRPC-C++/src/core/lib/gprpp/memory.h:22:10: 'grpc/support/port_platform.h' file not found
/Users/georg/Projekte/Apps/anyfinder/Pods/Down/Source/Renderers/DownASTRenderable.swift:10:8: Could not build Objective-C module 'libcmark'

```
## What did you do?

Install Down by adding it to the podfile with 
`  pod 'Down'
`
## What did you expect to happen?

Down to install and work as advertised.

## What happened instead?

I get two compiler warnings and cannot build my project anymore.

**I don't know if this could be related, but I am also using Google FirebaseFirestore in the project. Google recently switched their GRPC implementation from Objective-C gRPC framework to gRPC C++ (see https://firebase.google.com/support/release-notes/ios)**

**Comment by iwasrobbed** [comment]
Not sure what GRPC is, but if you can reproduce this without that dependency, feel free to reopen this issue. 

Often times a low-level dependency (like the error message given in `Pods/gRPC-C++/src/core/lib/gprpp/memory.h:22:10: 'grpc/support/port_platform.h' file not found`) will causer upper level dependencies to not build. Fix the lower level errors first and then see if everything else builds.

**Comment by ghowen** [comment]
Well, the thing is that without add the `Down` pod, my app compiles fine. 

Or in other words: Just by adding `pod 'Down'` to my podfile breaks the build. So I assumed that libcmark as a dependency of Down is using GRPC and that this breaks things. 

Do you think this has nothing to do with Down?

**Comment by iwasrobbed** [comment]
libcmark doesn't do any sort of networking since it's just a CommonMark renderer. 

It's much more likely that Down sets a specific compiler type for itself (like you mentioned, C++, Objective-C++, version of C++, etc) and that conflicts with the one that GRPC sets for itself, which is why I mentioned setting each of those independently by going into the Pods project, selecting the respective library, and changing its build settings.

This is outside the scope of `Down` so unfortunately I can't be of further help. Feel free to ask on StackOverflow.com

**Comment by aelkady** [comment]
@ghowen @iwasrobbed I have run into this exact issue as well (Down/gRPC incompatibility) and I have found that forcing `Down` to point to v0.5.2 in your pod file (`pod 'Down', '0.5.2'`) will fix the compilation error. This leads me to believe that something changed in `Down` after v0.5.2 to cause this issue. Would either of you have any additional insight into this?

**Comment by garyhooper** [comment]
I have the same issue.  Forcing Down to v0.5.2 solves the problem Upgrading to latest 0.6.2 causes the compile error. I am also using FirebaseFirestore (1.0.0) and thus gRPC-C++ (0.0.6), gRPC-Core (1.17.0).

**Comment by iwasrobbed** [comment]
There is a fork you can use here for now until someone patches the main libcmark repo: https://github.com/iwasrobbed/Down/pull/125

**Comment by iwasrobbed** [comment]
Possibly fixed in https://github.com/iwasrobbed/Down/pull/125

**Comment by aelkady** [comment]
Just tried the latest version (0.6.5) and this seems to have done the trick. Thanks all!
