### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by matphillips** [iwasrobbed/Down#12]
Download, open in Xcode, build, locate Down.framework folder, drag to target Xcode project.
However, "Use of unresolved identifier 'Down' " so I've missed a step somewhere.

Don't want to use carthage or pods, so how to install?
Thanks.

**Comment by azeff** [comment]
You need to import Down module (`import Down`).

**Comment by matphillips** [comment]
of course, thanks.
Builds now but crashes at runtime with: 
```
dyld: Library not loaded: @rpath/Down.framework/Down
  Referenced from: /Users/phillipsm/Library/Developer/CoreSimulator/Devices/F2454097-CE3E-47FC-959D-4432C1C65C10/data/Containers/Bundle/Application/E366A40D-8953-4B24-A83A-FA7C1F759084/LaCE3.app/LaCE3
  Reason: image not found
(lldb) 
```

I resolved that by removing the library from the "Linked frameworks and libraries" section of the target and adding it to the "Embedded binaries" section. Then it worked. 
Thanks.
