### ISSUE TITLE
[Attributed Strings] Line spacing more than expected

### ISSUE THREAD

**Issue by qwsdxcqwsdxc** [iwasrobbed/Down#121]
The spacing between each line and paragraphs is more than intended space. (Eg 1 newline \n = 2 or more \n) 

The linespacing value does not seem to reflect when converting the Markdown text to attributed string.

**Comment by iwasrobbed** [comment]
Can you please specify how you're rendering the Markdown? @qwsdxcqwsdxc

**Comment by iwasrobbed** [comment]
This is more an issue within WebKit since it's the primary renderer of attributed strings from HTML, which is what Down does under the hood.

**Comment by iwasrobbed** [comment]
This should be easier once #100 and #81 are done; for now, it's just a limitation of WebKit. Feel free to clean the data prior to rendering

**Comment by iwasrobbed** [comment]
FYI: this has been further improved with a default `Styler` via https://github.com/iwasrobbed/Down/pull/177
