### ISSUE TITLE
support for audio markdown?

### ISSUE THREAD

**Issue by jatinverma007** [iwasrobbed/Down#122]
Please help prevent duplicate requests before submitting a new one:

* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request

## Is your feature request related to a problem? Please describe.

ℹ A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  

## Describe the solution you'd like

ℹ A clear and concise description of what you want to happen.

## Describe alternatives you've considered

ℹ A clear and concise description of any alternative solutions or features you've considered.

**Comment by iwasrobbed** [comment]
There is an ongoing discussion here: https://talk.commonmark.org/t/embedded-audio-and-video/441/98

Once finalized, it will need doing in the main libcmark repo: https://github.com/commonmark/cmark
