### ISSUE TITLE
Use with storyboards

### ISSUE THREAD

**Issue by ahmedabadie** [iwasrobbed/Down#123]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Added a DownView to a storyboard.

## What did you expect to happen?

Load the DownView normally.

## What happened instead?

```swift
fatalError("init(coder:) has not been implemented")
```

I'm not sure if that's an intended behavior, but I expect it to work normally when using storyboards.

**Comment by iwasrobbed** [comment]
Feel free to fork and open a pull request with the required (simple) changes. Open source is open to help from the community, not just my responsibility
