### ISSUE TITLE
Support SwiftPM

### ISSUE THREAD

**Issue by mshibanami** [iwasrobbed/Down#128]
Please help prevent duplicate requests before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request

This library doesn't support the Swift Package Manager so it'd be nice if it did. 

## Is your feature request related to a problem? Please describe.

I tried to use this library in my CLI program written in Swift but I couldn't.

## Describe the solution you'd like

- Add `Package.swift`
- Changing the structure might be also needed

## Describe alternatives you've considered

Nothing.

**Comment by iwasrobbed** [comment]
I'm happy to accept pull requests from the community; closing this one since it didn't garner much attention in https://github.com/iwasrobbed/Down/issues/61

**Comment by iwasrobbed** [comment]
FYI, this is being done in https://github.com/iwasrobbed/Down/pull/150
