### ISSUE TITLE
Support Images

### ISSUE THREAD

**Issue by ogezue** [iwasrobbed/Down#13]
Your framework seems to be really great!
I tried it with http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html and everything seems to be working except images. Is this possible?

**Comment by iwasrobbed** [comment]
It wouldn't work with that example because they use a locally hosted image file versus specifying a URL

e.g.

```markdown
![example image](example-image.jpg "An exemplary image")
```

versus

```markdown
![example image](http://example.com/example-image.jpg "An exemplary image")
```
