### ISSUE TITLE
Swift 4/5 compatibility

### ISSUE THREAD

**Issue by JetForMe** [iwasrobbed/Down#131]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

I'm trying to use Carthage to include Down in my Xcode 10.2/Swift 5 project. But the Down project specifies Swift 4, and I get incompatibility errors when trying to compile/link against it.

## What did you do?

Created a new Swift 5 project. Set up Carthage to include Down. Compiled, got an error "The following binaries use incompatible versions of Swift:" referencing my app and the Down framework.

## What did you expect to happen?

This is going to be tricky, isn't it? I need to be able to compile dependencies with Swift 5 via Carthage. I tried modifying the project, and it builds and the tests pass, but if I update with Carthage it reverts to Swift 4.

## What happened instead?

if I update with Carthage it reverts to Swift 4. Need a version that bumps the Swift version, but there's a backward-compatibility issue.

**Comment by iwasrobbed** [comment]
I don't use Carthage but I imagine if we just bump to Swift 5 with whatever
changes that ensues, then others can just use an older tag if they still
need Swift 4 or below, no?

**Comment by JetForMe** [comment]
For sure, until they need features or bugfixes you offer but need pre-Swift-5 compatibility. I'm all for staying on the bleeding edge, but I think this is a problem that's going to affect a lot of Carthage projects (or really, any project that uses third-party libraries).

**Comment by JetForMe** [comment]
I'm conflating the Swift 5 compiler version with the selected language dialect. All we need is to use the Swift 5 compiler; we don't need to change the setting inside the Xcode project. So, building from source via Carthage should work just fine, once everything is set up properly.

**Comment by iwasrobbed** [comment]
Updating to Swift 5.0 in https://github.com/iwasrobbed/Down/pull/145
