### ISSUE TITLE
[Documentation] AST API

### ISSUE THREAD

**Issue by dachev** [iwasrobbed/Down#134]
Xcode's autocomplete does not work with the AST type. Combined with the lack of documentation, it's hard to tell how ASTs are meant to be used. It would be very helpful to have a short example in the README page.

**Comment by iwasrobbed** [comment]
Happy to accept pull requests with docs or to roll this into a PR supporting https://github.com/iwasrobbed/Down/pull/132

**Comment by johnxnguyen** [comment]
I'll document my AST node wrappers and include it in my PR.
