### ISSUE TITLE
0.7.0 problems with NSAttributedString.Key

### ISSUE THREAD

**Issue by Sethmr** [iwasrobbed/Down#139]
I just updated to 0.7.0 and noticed that the NSAttributedStringKey in Styler.swift was not renamed to NSAttributedString.Key. The pod's compile sources claim that Swift 5 is the desired  version of swift, so this would infer that either the compile source is wrong or there is a tiny bug in the SDK. I will go back to the previous version until a new one comes out. Thanks for your time!

**Comment by phoney** [comment]
Right. That name changed in swift 4.2 so it needs to be updated.

**Comment by iwasrobbed** [comment]
@Sethmr The [podspec doesn't set a swift version yet](https://github.com/iwasrobbed/Down/blob/master/Down.podspec) so you can do so manually for now in the post install.

It's likely defaulting to whatever your project is set to

**Comment by phoney** [comment]
Is the intention to support multiple versions of swift or just the latest? That code could be wrapped in #if swift(>= 4.2) to support multiple versions if that's what's desired. The current code though is swift 4.0 I think.

**Comment by iwasrobbed** [comment]
Correct, it's Swift 4.0 for now. Pods can support Swift versions lower than and independent of the target app itself, so this sounds more like the `swift_version` just needs setting in the podspec and it'll resolve correctly. You can also do it in the post install like I said above as a workaround

**Comment by iwasrobbed** [comment]
Just an FYI, I re-pushed version `0.7.0` to CocoaPods with this Swift version (`4.0`) set so let me know if you have any other issues

**Comment by iwasrobbed** [comment]
Updating to Swift 5.0 in https://github.com/iwasrobbed/Down/pull/145
