### ISSUE TITLE
.toAttributedString stylesheet parameter

### ISSUE THREAD

**Issue by TheMoon2000** [iwasrobbed/Down#158]
The README only briefly mentions the 'stylesheet:' property (type: String?) as a parameter in .toAttributedString() call. However, the syntax for such a stylesheet is very vague.

> but you can override this by passing in your own, using the 'stylesheet:' parameter.

 This is the only line of text that talks about the 'stylesheet:' parameter. Can you give me some examples of what the stylesheet can be? Does it follow CSS format?

**Comment by NicolasLourenco** [comment]
Hello,
For example:
```
static let defaultMarkdownStylesheet =
    """
      body { font: -apple-system-body }
      h1 { font: -apple-system-title1 }
      h2 { font: -apple-system-title2 }
      h3 { font: -apple-system-title3 }
      h4, h5, h6 { font: -apple-system-headline }
    """
```

**Comment by iwasrobbed** [comment]
Thanks @NicolasLourenco 👍 Going to close this one, but feel free to open a PR if you'd like to add documentation to the readme or code
