### ISSUE TITLE
Disable zoom WebView

### ISSUE THREAD

**Issue by Xopoko** [iwasrobbed/Down#16]
How to disable zoom in/out in this view?

**Comment by iwasrobbed** [comment]
If you're talking about the `DownView` web view, you should likely add this meta tag to [the index.html file that gets rendered](https://github.com/iwasrobbed/Down/blob/master/Resources/DownView.bundle/index.html) but keep in mind that this may not work in iOS 10 and above. 

```html
<meta name="viewport" content="width=device-width, user-scalable=no" />
```

You can find more info about disabling zoom on http://stackoverflow.com/q/4389932/308315

**Comment by mbecker** [comment]
Not the perfect solution because double tap or scrolling down and the pinching out seems to work.

The better solution for me is to add:
```swift
extension DownView: UIScrollViewDelegate {
    public func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return nil
    }
}
```

Set the webview's scrollview delegate in DownView.init():
```swift
self.scrollView.delegate = self
```

Change the viewport in index.html to:
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

Change the font scale in the css file to whatever you like:
```css
-ms-text-size-adjust: 80%;
-webkit-text-size-adjust: 80%;
```
