### ISSUE TITLE
Help: Get Raw String without Markdown

### ISSUE THREAD

**Issue by cliftonlabrum** [iwasrobbed/Down#167]
There are cases where I want to allow the user to enter Markdown, but I want to be able to render what they've typed **_without_** the Markdown in it. For example, imagine a table list of emails where a couple lines of preview text are shown, or in a push notification... seeing `**stuff**` in that context looks weird.

Is there a way to parse the Markdown string into a raw string without any of the `*``_``#` characters--essentially removing all the Markdown?

**Comment by iwasrobbed** [comment]
Hi @cliftonlabrum 👋 That use case is outside the scope of Down, but you can try rendering it to an [attributed string and then calling `.string` on it](https://developer.apple.com/documentation/foundation/nsattributedstring/1412616-string)

**Comment by cliftonlabrum** [comment]
Ah, that's a great idea! Thank you! 🙏🏼
