### ISSUE TITLE
Help: Set Default Font

### ISSUE THREAD

**Issue by cliftonlabrum** [iwasrobbed/Down#168]
I've been searching through the documentation and the issues, and I don't see a clear way to set the default font for the entire `NSAttributedString`. If you apply the font as an attribute after Down renders the string, it will overwrite all the other attributes.

Is there a way to set a default font and then have Down render the rest of the string as it should (bold, italic, etc.?

I see the `Styler` option, but I don't see any documentation on how to use it.

Thanks!

**Comment by iwasrobbed** [comment]
Does this work for you?

https://github.com/iwasrobbed/Down#parsing-api

>// NSAttributedString representation of the rendered HTML;
>// by default, uses a stylesheet that matches NSAttributedString's default font,
>// but you can override this by passing in your own, using the 'stylesheet:' parameter.

**Comment by cliftonlabrum** [comment]
That's interesting. What kind of `String` does the `stylesheet` parameter take? 

Does it use raw CSS properties like:
```
down.toAttributedString(stylesheet:"font-family: 'Avenir'")
```
Or does it take a full CSS file in the form of a `String` like:
```
let style = "body{ font-family: 'Avenir'; }"
down.toAttributedString(stylesheet: style)
```
Thanks!

**Comment by freshking** [comment]
Something like this (taken from `DownAttributedStringRenderable.swift`):

```Swift
let style = "* {font-family: Helvetica } code, pre { font-family: Menlo }"
down.toAttributedString(stylesheet: style)
```

**Comment by cliftonlabrum** [comment]
Ah, okay. Makes sense. Thank you!

**Comment by iwasrobbed** [comment]
FYI: this is further possible via the default `Styler` via https://github.com/iwasrobbed/Down/pull/177

**Comment by nselvapandian** [comment]
let defaultStylesheet = "* {font-family: SFProDisplay-Semibold; font-size: 15px}"

Is this the correct format to set system font? Can someone guide me?
