### ISSUE TITLE
Framework crashes when converting to NSAttributedString

### ISSUE THREAD

**Issue by TheMoon2000** [iwasrobbed/Down#171]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I tried to render a particular string using this markdown library and my program crashed right away:
```swift
try? Down(markdownString: "Sample*description*.").toAttributedString()
```

## What did you expect to happen?

Of course, I expected no error to occur. The attributed string should be:

Sample*description*.

It was an accident that I forgot to include a space between the words, but it turned out that I discovered a bug.

**EDIT**: I tried to render the string `Sample *description*.` (same thing but with a space) but the same error occurred. Now I have no idea why the framework should crash.

**EDIT 2**: The problem was fixed after I ran the code in a `DispatchQueue.main.async {}` block.

## What happened instead?

Xcode gave the following message:

> Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]'

If it's not very clear, try running the same line of code on your computer. This problem is easy enough to replicate.

**Comment by iwasrobbed** [comment]
Hi there 👋 I was unable to repro in the example app. Looks like you found the real issue which is `NSAttributedString`s don't render HTML on background threads. Please use the other background-safe API if that's needed https://github.com/iwasrobbed/Down/blob/master/Source/Renderers/DownAttributedStringRenderable.swift#L47

`NSAttributedString` docs: https://developer.apple.com/documentation/foundation/nsattributedstring/1524613-initwithdata

>The HTML importer should not be called from a background thread
