### ISSUE TITLE
Support for local images

### ISSUE THREAD

**Issue by LeoGloold** [iwasrobbed/Down#173]
I can't seem to get images that are stored locally in the app bundle to load in markdown. I've tried:
```
let url = Bundle.main.url(forResource: "1", withExtension: "jpg")!
let markdownString = "![image](\(url))"
```
And:
```
let markdownString = "![image]("1.jpg")"
```

**Comment by iwasrobbed** [comment]
Hi there 👋 Please follow the issue template next time; you seem to have skipped this step:

>* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

That would lead you to: https://github.com/iwasrobbed/Down/issues/40

Thanks.
