### ISSUE TITLE
GIFF Support

### ISSUE THREAD

**Issue by goelay** [iwasrobbed/Down#174]
Giff file not playing? Any idea on how to play it.

**Comment by iwasrobbed** [comment]
Image support works fine. You can see that in the example app. Please investigate this more thoroughly next time prior to opening an issue for it.

If you're trying to load local image files, see #40 

![gif](https://user-images.githubusercontent.com/317671/64424618-8dc9a980-d077-11e9-82e7-1e31d3c8bfae.gif)
