### ISSUE TITLE
Error: 'cmark_export.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by rubensantiago** [iwasrobbed/Down#175]
# Report
Manually changing these brackets to quotes does indeed fix this issue, but updating the pod will revert the manual changes made. 

Unfortunately, this is not tenable on a build server that downloads fresh copies of dependencies periodically.

## What did you do?

pod install

## What did you expect to happen?

Compile without modifying the source code

## What happened instead?

`Error: 'cmark_export.h' file not found with <angled> include; use "quotes" instead
File: project-root/Pods/Down/Source/cmark/cmark.h:5`

**Comment by iwasrobbed** [comment]
Hi @rubensantiago 👋 We'll need a bit more info please: Xcode version, CocoaPods version, Down version at a minimum

A sample project repro'ing this (or repro'ing it with the `Example` app included in the repo) is great appreciated. 

Thanks!

**Comment by iwasrobbed** [comment]
Going to close this out since we have not received any follow up information.

**Comment by Salman88** [comment]
root/Pods/Down/Sources/cmark/cmark.h:5:10: 'cmark_export.h' file not found with <angled> include; use "quotes" instead
#include <cmark_export.h>
         ^~~~~~~~~~~~~~~~
root/Pods/Down/Sources/cmark/cmark.h:6:10: 'cmark_version.h
<img width="1164" alt="Xcode Version 13 2 1" src="https://user-images.githubusercontent.com/1101760/148608707-78bda476-5093-4753-b0d9-177be57f956a.png">
<img width="1116" alt="Xcode Version 12 5 1" src="https://user-images.githubusercontent.com/1101760/148608708-5e068171-b86e-47fb-837a-159c3e56155e.png">
' file not found with <angled> include; use "quotes" instead

Xcode version Version 12.5.1, Version 13.2.1 
Cocoa pod version 1.10.2 and 1.11.2

**Comment by Salman88** [comment]
Manually changing file by adding **quotes** works but on build server it fails

Tested with 
**Xcode version Version 12.5.1, Version 13.2.1** 
**Cocoa pod version 1.10.2 and 1.11.2**
**Down version (0.11.0)**


```root/Pods/Down/Sources/cmark/cmark.h:5:10: 'cmark_export.h' file not found with <angled> include; use "quotes" instead
#include <cmark_export.h>
         ^~~~~~~~~~~~~~~~
root/Pods/Down/Sources/cmark/cmark.h:6:10: 'cmark_version.h
```
**Image on Xcode Version 13.2.1**
<img width="1164" alt="Xcode Version 13 2 1" src="https://user-images.githubusercontent.com/1101760/148608707-78bda476-5093-4753-b0d9-177be57f956a.png">

**Image on Xcode Version 12.5.1**
<img width="1116" alt="Xcode Version 12 5 1" src="https://user-images.githubusercontent.com/1101760/148608708-5e068171-b86e-47fb-837a-159c3e56155e.png">


' file not found with <angled> include; use "quotes" instead

**Comment by VatanaChhorn** [comment]
I am still experiencing the same issue on Nov 2022. Are there any updates upon this besides manually changing to the quotation marks? @iwasrobbed

**Comment by mrr-fiftytwo** [comment]
I am still experiencing the same issue on 16th Dec 2022. With 
Xcode version Version 14.2
Cocoa pod version 1.11.3
Down version (0.11.0)
