### ISSUE TITLE
Update Framework with Swift 5.1

### ISSUE THREAD

**Issue by goelay** [iwasrobbed/Down#178]
Please help prevent duplicate requests before submitting a new one:

* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request

## Is your feature request related to a problem? Please describe.

ℹ A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  

## Describe the solution you'd like

ℹ A clear and concise description of what you want to happen.

## Describe alternatives you've considered

ℹ A clear and concise description of any alternative solutions or features you've considered.

**Comment by iwasrobbed** [comment]
I'm happy to accept a pull request with these minor changes @goelay

**Comment by iwasrobbed** [comment]
Closed via #204
