### ISSUE TITLE
Please add Styler example in the documentation

### ISSUE THREAD

**Issue by tikekar** [iwasrobbed/Down#179]
Please help prevent duplicate requests before submitting a new one:

* [ X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request
Please add Styler example in the documentation
## Is your feature request related to a problem? Please describe.
We use custom fonts and somehow if I use down.toAttributedString() all my bold, italics etc do not work. I am assuming that may be a styler might help? But not sure how to use it. A sample might help

ℹ A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  

## Describe the solution you'd like
I am assuming that may be a styler might help? But not sure how to use it. A sample might help

ℹ A clear and concise description of what you want to happen.

## Describe alternatives you've considered

ℹ A clear and concise description of any alternative solutions or features you've considered.

**Comment by iwasrobbed** [comment]
Hi @tikekar 👋  This should be closed via https://github.com/iwasrobbed/Down/pull/177
