### ISSUE TITLE
Define custom fonts

### ISSUE THREAD

**Issue by georgbachmann** [iwasrobbed/Down#18]
Is there any way to define custom fonts to use for the output?
I'd need attributed strings where I can define which base-font to use, also which font for h1, h2, ...

Is that anyhow possible? I've seen you basically just give the input to cmark, but couldn't find any possibility to customize any font :(

Am I just missing something here?

**Comment by iwasrobbed** [comment]
@georgbachmann If you're rendering it as an attributed string, you should format it using `NSAttributedString` api's. More info https://developer.apple.com/reference/foundation/nsattributedstring

There are a lot of examples on StackOverflow as well for customizing attributed strings (e.g. rendering from html w/ custom fonts, etc) so I'd encourage exploring there first. This is just meant to be a presentation agnostic converter.

Duplicates #14

**Comment by georgbachmann** [comment]
Sure, I am already reformatting the attributed string to match the style I need. I was just wondering if it's possible to create the attributed string already the way I want it to be. That would be the better solution I guess than having to reformat afterwards. Also that way I can only assume which type of text (h1, h2, h3, ...) I am changing based on the font it currently uses, which is not that super sexy, is it?
Anyway... for what I need, the `NSAttributedString` APIs are enough... cheers

**Comment by iwasrobbed** [comment]
@georgbachmann Your best bet is to read the man pages for the underlying library [cmark](https://github.com/jgm/cmark);  there are unfortunately very limited options at present

**Comment by iwasrobbed** [comment]
Please see the new AST functionality for rendering and customizing attributed strings: https://github.com/iwasrobbed/Down/pull/132
