### ISSUE TITLE
incorrect parse for string that is a mixture of markdown and html

### ISSUE THREAD

**Issue by marwakharbech** [iwasrobbed/Down#180]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report
A string that has both markdown and html in it, isn't parsed correctly. the markdown was ignored.
## What did you do?

ℹ   
`
let myText = "#Taxation   \n  <br \/><img style=\"width: 100%;\" src=\"https:\/\/somewebsite.com\/img\/25\/header_taxation.jpg\" \/><br \/>Payments <br \/><a class=\"btn\" style=\"color:white;font-weight:bold;background-color:#67ae3c\" target=\"_blank\" href=\"https:\/\/somewebsite.com\"><span style=\"padding:5px\">PAY NOW<\/span><\/a>"
  let down = Down(markdownString: urlString)
   guard let html = try? down.toHTML(.unsafe) else { return }
   print("Taxation text", html)
`

## What did you expect to happen?

ℹ it parses the markdown into html

## What happened instead?

ℹ `Taxation text <p>#Taxation<br />
<br /><img style="width: 100%;" src="https://uat-magog.bciti.info/img/25/header_taxation.jpg" /><br />Paiements électroniques par internet <br /><a class="btn" style="color:white;font-weight:bold;background-color:#67ae3c" target="_blank" href="https://transphere.acceo.com/magog/#/U3001"><span style="padding:5px">EFFECTUER UN PAIEMENT MAINTENANT</span></a></p>`

**Comment by iwasrobbed** [comment]
Hi @marwakharbech 👋  If you feel there's a rendering error in `cmark` (the rendering engine used), please file it in the upstream repo: https://github.com/commonmark/cmark/issues

We're happy to update here once it's resolved. Thanks!
