### ISSUE TITLE
How to change text color?

### ISSUE THREAD

**Issue by zhuravel-sergey** [iwasrobbed/Down#182]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with what happened instead (e.g. the issue).  

Please see screenshot

<img width="1281" alt="screen" src="https://user-images.githubusercontent.com/7910769/67128616-e5297080-f204-11e9-8214-7480150c023c.png">

**Comment by iwasrobbed** [comment]
Feel free to open a pull request making that public

**Comment by iwasrobbed** [comment]
Closed via https://github.com/iwasrobbed/Down/pull/184
