### ISSUE TITLE
Table are not render

### ISSUE THREAD

**Issue by fdddf** [iwasrobbed/Down#183]
Please help prevent duplicate issues before submitting a new one:

* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

sample code:
```
## Tables
aaaa | abbb
-- | --
content a | content b




| Option | Description |
| ------ | ----------- |
| data   | path to data files to supply the data that will be passed into templates. |
| engine | engine to be used for processing templates. Handlebars is the default. |
| ext    | extension to be used for dest files. |

Right aligned columns

| Option | Description |
| ------:| -----------:|
| data   | path to data files to supply the data that will be passed into templates. |
| engine | engine to be used for processing templates. Handlebars is the default. |
| ext    | extension to be used for dest files. |
```

## What did you expect to happen?

render the table correctly

## What happened instead?

showing the original code

**Comment by iwasrobbed** [comment]
Please don't waste others' time by not searching existing issues. That's why the checkbox is there in every issue template (which you did not check)

https://github.com/iwasrobbed/Down/issues/36
