### ISSUE TITLE
Issue with markdown render/convert to attribute string on macOS latest version

### ISSUE THREAD

**Issue by sirily11** [iwasrobbed/Down#185]
Cannot use the either down.toAttributedString() and DownView on MacOS.  The error was shown when using down.toAttributedString()
<img width="1231" alt="截屏2019-10-27上午3 33 30" src="https://user-images.githubusercontent.com/32106111/67631917-9d40c400-f86a-11e9-929e-4435f3f12300.png">
And following error was thrown when using DownView
<img width="1389" alt="截屏2019-10-27上午3 35 52" src="https://user-images.githubusercontent.com/32106111/67631938-e4c75000-f86a-11e9-93bf-3eacb5029759.png">

The markdown string I use is simply a "Hello world" string. I also tried using the example from readme, but failed. The project also using swiftUI with NSViewRepresentable to wrap the DownView.

**Comment by sirily11** [comment]
This also happens when using it in ios project

**Comment by sirily11** [comment]
Ok. I got the solution. If you are using SwiftUI and bind this view using UIViewRepresentable or NSViewRepresentable, then toNSAttributedString should be running inside DispatchQueue.main.async. Otherwise, it will throw an error. I don't know the reason.

**Comment by rob-keepsafe** [comment]
Because UIKit doesn't work on background threads. This isn't just for SwiftUI, but iOS in general.
