### ISSUE TITLE
Is the text supposed to be rendering this large?

### ISSUE THREAD

**Issue by codyaweber** [iwasrobbed/Down#186]
* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Tried rendering README.md (copied straight from [raw](https://raw.githubusercontent.com/iwasrobbed/Down/master/README.md))

```
import UIKit
import Down

class QuickViewController: UIViewController {
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        setUpDownView()
    }
    
    private func setUpDownView() {
        let dv = try! DownView(frame: view.bounds, markdownString: mdString) {
            print("Loaded successfully.")
        }
        view.addSubview(dv)
    }
}
```

## What did you expect to happen?

The DownView to render as shown in the README.md:

<img src="https://user-images.githubusercontent.com/11325098/67813909-1a418880-fa79-11e9-93db-770bcf949fec.png" width="244" height="434">

## What happened instead?

The DownView renders, but appears zoomed, or the text is just displaying larger? It's the same with any other markdown I use. Is this expected behavior that must be overridden in the CSS, or am I doing something wrong?

<img src="https://user-images.githubusercontent.com/11325098/67813945-30e7df80-fa79-11e9-89a6-5416e791f708.png" width="200" height="434">

**Comment by smittytone** [comment]
Another questioner, same question!

**Comment by iwasrobbed** [comment]
You can inject your own CSS to change font size using a custom bundle: https://github.com/iwasrobbed/Down/blob/master/Source/Views/DownView.swift#L27

You can see what `DownView` uses in the `DownView.bundle/css` folder and just modify the line around `font-size:1.5em;line-height:1.6`
