### ISSUE TITLE
App using xcframework with Down pod dependency causes crash

### ISSUE THREAD

**Issue by deathByLiche** [iwasrobbed/Down#187]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I created an xcframework that has a dependency on Down, then integrated the framework into an app that pulls Down in via Cocoapods. 

## What did you expect to happen?

I expected to be able to call methods from the framework in the app that relied on Down.

## What happened instead?

There is an EXC_BAD_ACCESS crash anytime the app calls a method from the framework that uses Down. 

I've successfully integrated a separate xcframwork with a third-party dependency in this way, so I'm guessing this is related to how Down is referencing libcmark. 

I've attached two sample projects which demonstrate the issue. The xcframework linked in the TestApp was generated from the TestFramework project by running the build_xcframework shell script included in the folder.

[DownTest.zip](https://github.com/iwasrobbed/Down/files/3796111/DownTest.zip)

**Comment by iwasrobbed** [comment]
Apologies @deathByLiche, but this is not the place for help debugging your setup. StackOverflow is a much better forum for that.
