### ISSUE TITLE
How to update DownView content and keep the style?

### ISSUE THREAD

**Issue by li-xinyang** [iwasrobbed/Down#19]
I can add a `DownView` to my view (use code below) but how can I update the content inside it?

```
    let cardFrontStr = "Use chained optional to simplify code below,\n\n```\nvar display: UILabel?\nif let label = display {\n  if let text = label.text {\n    let x = text.hasValue\n    // ...\n  }\n}\n```"
    let cardfrontView = try? DownView(frame: cardfront.bounds, markdownString: cardFrontStr)
    cardfront.addSubview(cardfrontView!)
```

Since the DownView is extended from `WebView`, I can update the content and `loadHTMLString`; however, the DownView style is gone after I have done so.

        let down = Down(markdownString: "`test`")
        let newStr = try? down.toHTML()
        cardbackView?.loadHTMLString(newStr!, baseURL: nil)

**Comment by iwasrobbed** [comment]
@li-xinyang Thanks for opening an issue. This should be easy enough to add and I will push out a fix for it soon (today or tomorrow)

**Comment by iwasrobbed** [comment]
@li-xinyang Closing this via #22
