### ISSUE TITLE
Regression: single newline syntax not working (any variety)

### ISSUE THREAD

**Issue by gsbernstein** [iwasrobbed/Down#191]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Upgraded from 0.6.2 to 0.9.0

## What did you expect to happen?

No breaking changes

## What happened instead?

Newline syntax stopped working:

0.9.0 | 0.6.2
--- | ---
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-21 at 16 18 48](https://user-images.githubusercontent.com/16406453/69388416-a6605d80-0c7d-11ea-844e-432a086bb6df.png)|![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-21 at 16 38 19](https://user-images.githubusercontent.com/16406453/69388427-ac563e80-0c7d-11ea-8f8b-391ab7bf3cff.png)

We tried `<br />` and `\n` which both did nothing, while `\n\n` added way too much space.

**Comment by gsbernstein** [comment]
@ericgroom

**Comment by ericgroom** [comment]
To add some extra context, we are using css styling and converting to an attributed string. Within the string displayed, we had been using `<br />` to create a newline as seen in the photo, but this no longer seems to work on the latest version.

**Comment by iwasrobbed** [comment]
If you're using CSS styling, then it sounds like you're also using the WebKit API for rendering of the HTML. There's not a whole lot Down can do about how WebKit renders things.

You're welcome to switch to the new attributed string APIs and you'll have much more control over rendering that way, in addition to performing background rendering.

e.g. https://github.com/iwasrobbed/Down/blob/master/Source/AST/Styling/Stylers/DownStyler.swift#L24
