### ISSUE TITLE
Swift Packege maneger?

### ISSUE THREAD

**Issue by BenjiMandel** [iwasrobbed/Down#194]
Hi,
I was looking for a good Markdown parser for ios using swift, and I got recommended your project, Down. 
Does your project support SwiftPackageManeger? or only manual, Carthage and cocoa pods?

thanks,
Benji

**Comment by unnamedd** [comment]
Hi @BenjiMandel,

try to follow this article here:
https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app

using this URL:
https://github.com/iwasrobbed/Down.git

then, you should be able to add Down to your project.

**Comment by BenjiMandel** [comment]
Hi
Thx for the reply!!
Will do that!!!!
I had a lot!
Regards,
Benji

**Comment by unnamedd** [comment]
Good luck and if you need anything else, call us here! ;)

**Comment by unnamedd** [comment]
@iwasrobbed I guess you can close this issue here. ;D

**Comment by iwasrobbed** [comment]
Thanks for helping here @unnamedd 👍
