### ISSUE TITLE
Swift UI Support

### ISSUE THREAD

**Issue by christophschnabl** [iwasrobbed/Down#199]
* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request

e.g. by providing an example on how to use with SwiftUI

**Comment by iwasrobbed** [comment]
`DownView` is just a `WKWebView` subclass, so you should be able to find information on how to use that with SwiftUI on stackoverflow, etc.

**Comment by MrWoWander** [comment]
I offered my example on working with SwiftUI in #260
