### ISSUE TITLE
Release fixes made after 0.9.0

### ISSUE THREAD

**Issue by vzsg** [iwasrobbed/Down#201]
* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

Please make a new release from the master branch to make important fixes to the Styler available, or list any factors that might be hindering that release.

## What did you do?

Installed the most recently available version of Down in my project via CocoaPods.

## What did you expect to happen?

Being able to use StaticColorCollection and co. that have been fixed by #184, merged at the end of October 2019.

## What happened instead?

0.9.0 is installed, which was tagged on October 7th.

**Comment by rob-keepsafe** [comment]
Hi @vzsg 👋 You can just point to a specific branch instead; I don't plan on cutting a release for the time being 

More info https://stackoverflow.com/a/39930762/308315

**Comment by vzsg** [comment]
Thanks for the notice. Out of desperation, that's what I've done before writing the issue.

It's a pity though. Even if CP locks against a commit hash, a proper release would be easier to reason about.
