### ISSUE TITLE
SwiftPM : Resolve apparent version incompatibility with swift-snapshot-testing

### ISSUE THREAD

**Issue by stevebaranski** [iwasrobbed/Down#202]
* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

1. I cloned the `Down` repository.
1. From the root of the directory of this cloned repository, I opened the workspace by issuing this command: `xed .`
1. I attempted to build the project.

## What did you expect to happen?

For an iOS device target, I expected the library to build (Cmd-B) and/or test (Cmd-U) successfully.

## What happened instead?

The Build attempt failed, with the following error:
```
No such module 'SnapshotTesting'
```

This impacts both `StylerTestSuite.swift` & `VisitorTests`, which include:
```
import SnapshotTesting
```

## Additional context

- The preceding steps _do work_ if I execute them against a branch created from the previous tag (i.e., `v0.8.6`).
- It appears that the `SnapshotTesting` dependency was [recently introduced](https://github.com/iwasrobbed/Down/pull/177/).
- I intended to submit a pull request proposing changes to `Package.swift` that account for this dependency, but incompatibilities exist between the minimum required deployment targets of each component (see below).

|Platform|[`Down`](https://github.com/iwasrobbed/Down/blob/master/Down.podspec#L13-L15)|[`SnapshotTesting`](https://github.com/pointfreeco/swift-snapshot-testing/blob/master/SnapshotTesting.podspec#L29-L31)|
| --- | --- | --- |
| iOS | 9.0 | 10.0 |
| macOS | 10.11 | 10.10 |
| tvOS | 9.0 | 10.0 |

## Questions

1. This _was_ surfaced in #165, but the impact to SwiftPM support might not have been considered at that time. Does the value of these snapshot tests justify upgrades to the minimum deployment target for iOS & tvOS?
1. Is it there a more limited scope with which the package dependency can be imported in `Package.swift`?

**Comment by iwasrobbed** [comment]
@stevebaranski I'd be okay with bumping support to iOS 10+ and will happily accept any PRs against that if you have the time to test and make sure it resolves it for you. Anyone needing support for earlier OS versions can easily do so

**Comment by iwasrobbed** [comment]
Thanks for the very detailed issue by the way, it's refreshing 💯

**Comment by stevebaranski** [comment]
@iwasrobbed Upon further investigation, I noted that some of the files specified in the `testTarget` of `Package.swift` included those that imported `SnapshotTesting`. Excluding those files appeased SwiftPM, **without** requiring an update to the minimum deployment targets.

I expressed #203 for your consideration.

> Thanks for the very detailed issue by the way

No problem - thanks for your continued stewardship of `Down`!

**Comment by iwasrobbed** [comment]
Closed via #203
