### ISSUE TITLE
Unable to build Swift package in Xcode 11.4.1

### ISSUE THREAD

**Issue by SwiftDevJournal** [iwasrobbed/Down#209]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

1. Add Down to Swift Packages for Mac Cocoa app project with Xcode 11.4.1.
2. Use master branch as the rule for the Swift package.
3. Build the project.

## What did you expect to happen?

I expected the package to build and to be able to import Down. 

## What happened instead?

I get the following compiler errors:

> unknown type name 'cmark_reference_map'

For the following lines of code in the file inlines.h

```
void cmark_parse_inlines(cmark_mem *mem, cmark_node *parent,
                         cmark_reference_map *refmap, int options);

bufsize_t cmark_parse_reference_inline(cmark_mem *mem, cmark_chunk *input,
                                       cmark_reference_map *refmap);
```

I also get the error "Could not build Objective-C module libcmark" in the file BaseNode.Swift.

When I try to import Down, I get the following error message:

> No such Module Down

**UPDATE**

I get the same compiler errors when I clone the Down project from GitHub and try to build the Swift package.

**Comment by Luten** [comment]
Got the same error while copying sources of Down lib inside my project and trying to build it.
Xcode 11.4.1

Fixed it by adding `#include <references.h>` in inlines.h
But after that got bunch of errors:
```
: "_cmark_node_get_literal", referenced from:
: "_cmark_node_get_url", referenced from:
: "_cmark_node_get_list_type", referenced from:
: "_cmark_render_xml", referenced from:
: "_cmark_render_html", referenced from:
: "_cmark_parse_document", referenced from:
: "_cmark_render_man", referenced from:
: "_cmark_render_latex", referenced from:
: "_cmark_render_commonmark", referenced from:
: "_cmark_node_get_fence_info", referenced from:
: "_cmark_node_get_list_start", referenced from:
: "_cmark_node_free", referenced from:
: "_cmark_node_get_title", referenced from:
: "_cmark_node_first_child", referenced from:
: "_cmark_node_parent", referenced from:
: "_cmark_node_get_heading_level", referenced from:
: "_cmark_node_next", referenced from:
: "_cmark_node_get_type", referenced from:
: Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rob-keepsafe** [comment]
Hi there 👋 I don't use Swift PM but feel free to open a pull request if you have fixes and improvements to that build process

**Comment by KrisConrad** [comment]
I'm also getting the `Missing required module 'libcmark'` error when trying to include the project from SPM or Cocoapods.

**Comment by kengruven** [comment]
Have you tried upgrading Xcode?  There's an Xcode 11.5 now, which still supports every system that 11.4.x did.

I added "iwasrobbed/Down" as a Swift Package to a new Project in Xcode 11.5, and it built just fine.  Then I added the first couple lines from Down's README to that program (and logged it), and it was able to generate HTML from Markdown.  So, no problems with Down-via-SPM here.

**Comment by SwiftDevJournal** [comment]
I am able to build the Swift package in Xcode 11.6.
