### ISSUE TITLE
How to keep UITextView font style

### ISSUE THREAD

**Issue by RhusferJohn** [iwasrobbed/Down#21]
Hi, as I use this module it overrides the font of the textView. Is there any way to set the font when initialising Down?

`let down = Down(markdownString: markup) 
self.messageLabel.attributedText = try! down.toAttributedString()`

**Comment by iwasrobbed** [comment]
@RhusferJohn Please see #18 or #14 

>If you're rendering it as an attributed string, you should format it using NSAttributedString api's. More info https://developer.apple.com/reference/foundation/nsattributedstring
>
>There are a lot of examples on StackOverflow as well for customizing attributed strings (e.g. rendering from html w/ custom fonts, etc) so I'd encourage exploring there first. This is just meant to be a presentation agnostic converter.

**Comment by iwasrobbed** [comment]
Please see the new AST functionality for rendering and customizing attributed strings: https://github.com/iwasrobbed/Down/pull/132
