### ISSUE TITLE
Can't build with copied sources

### ISSUE THREAD

**Issue by Luten** [iwasrobbed/Down#211]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.
Presumably similar or somewhat connected issues I've found: 
  * #120 [Carthage] Missing required module 'libcmark'
  * #209 Unable to build Swift package in Xcode 11.4.1

# Report

## What did you do?

1. Copied contents of `Down/Source` into my project (I can't reference external frameworks)
2. Tried to build project

## What did you expect to happen?

I expected the project to build successfully 

## What happened instead?

1. Build failed with error: `unknown type name 'cmark_reference_map'` in inlines.h
    * Fixed it by adding `#include <references.h> in inlines.h`
2. Build failed with multiple errors: `No such module 'libcmark'`
    * Tried removing import (thought module is not needed when sources are in same project) - that was a wrong way

That all happens Xcode 11.4.1, Legacy Build System.
Gonna give a try on New Build System

Maybe there is a guide on using Down as copied sources?

P.S: building with Down as CocoaPods dependency works fine

**Comment by Luten** [comment]
Looks like `libcmark` module is used to import c code in swift, so removing import was a wrong way.

Then the problem is `No such module 'libcmark'`

**Comment by Luten** [comment]
Found that path to libcmark module.modulemap should be added to Swift Compiler - Import Paths.
Now receiving a lot of `Could not build module 'Foundation'` errors.
I suggest there is some importing loop there

**Comment by Luten** [comment]
Finally I've built it.
Can't say exactly what caused the problem, feels like some Xcode cache or bug resolved itself on 50th try of the settings that should work 
Mostly I did what all guides say:

* Add C sources
* Create modulemap (cmark/include/module.modulemap)

In Podspec:
* `spec.source_files` - add sources
* `spec.preservepath` - add modulemap and .inc files 
* `spec.pod_target_xcconfig` - add `'SWIFT_INCLUDE_PATHS' => '$(PODS_TARGET_SRCROOT)/<path to cmark modulemap>'`
* Also had to configure `spec.public_header_files`, as pod generated umbrella caused build errors like `unknown type name 'cmark_reference_map'` in #209

**Comment by rob-keepsafe** [comment]
I'm a bit confused @Luten ; are you integrating it via pods or manually?
