### ISSUE TITLE
Make BaseNode constructor public

### ISSUE THREAD

**Issue by ealymbaev** [iwasrobbed/Down#213]
I am trying to use my own custom `Visitor`.

I am using the same way as in `DownAttributedStringRenderable`:

```
let document = Document(cmarkNode: tree)
let visitor = AttributedStringVisitor(styler: styler, options: options)
return document.accept(visitor)
```

But `Document` initializer (actually `BaseNode` initializer) is not `public` and I am not able to create `Document` outside the library.

**Comment by johnxnguyen** [comment]
Hi @ealymbaev 👋 This has been brought up a few times already. Please see https://github.com/iwasrobbed/Down/pull/212

Indeed there is a lack of documentation that would regarding the AST, if I can find some free time I would like to fix that.

**Comment by ealymbaev** [comment]
By bad not searching for this issue. `wrap()` method does solve the issue.

Thank you for your help and great library!

**Comment by rob-keepsafe** [comment]
Just as a note, please follow the Bug Report template instead of deferring the work onto us. This is the very first line that you removed when filing this ticket:

>Please help prevent duplicate issues before submitting a new one:
>
>* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

**Comment by ealymbaev** [comment]
Sure... I will let you know when we add full implementation of your parser into our product, so that you can list it in Readme.
