### ISSUE TITLE
Line breaks between list items are not parsed correctly

### ISSUE THREAD

**Issue by ealymbaev** [iwasrobbed/Down#214]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I am trying to parse the following markdown example:

```
# First Example

- first item
- second item

# Second Example

- first item

- second item
```

## What did you expect to happen?

Most markdown renderers (e.g. `Github`) insert a line break between list items in `Second Example`.

## What happened instead?

But `Down` library does parse both first and second example same way. Here is the output of `DebugVisitor`:

```
Document
    ↳ Heading - L1
        ↳ Text - First Example
    ↳ List - type: Bullet
        ↳ Item
            ↳ Paragraph
                ↳ Text - first item
        ↳ Item
            ↳ Paragraph
                ↳ Text - second item
    ↳ Heading - L1
        ↳ Text - Second Example
    ↳ List - type: Bullet
        ↳ Item
            ↳ Paragraph
                ↳ Text - first item
        ↳ Item
            ↳ Paragraph
                ↳ Text - second item
```

I do understand that you use `cmark` library for parsing markdown nodes, but maybe I am missing something? Maybe some configuration options?

Or should I report this issue to `cmark` library repo?

**Comment by ealymbaev** [comment]
@johnxnguyen @rob-keepsafe any thoughts?

**Comment by johnxnguyen** [comment]
Hi @ealymbaev sorry for the delay. Indeed this is the behavior of `cmark`, whereby two list items separated by a single line break are considered to be part of the same list. I believe this is intentional and part of the [commonmark spec](https://daringfireball.net/projects/markdown/syntax#list).

Note however that two list items are separated by double newlines, then they both belong to separate lists:

```
1. I belong to list one.


1. I belong to list two
```

Does this help?

**Comment by ealymbaev** [comment]
Hi @johnxnguyen here is the quote from `commonmark spec` you provided:

```
If list items are separated by blank lines, Markdown will wrap the items in <p> tags in the HTML output. For example, this input:

*   Bird
*   Magic
will turn into:

<ul>
<li>Bird</li>
<li>Magic</li>
</ul>
But this:

*   Bird

*   Magic
will turn into:

<ul>
<li><p>Bird</p></li>
<li><p>Magic</p></li>
</ul>
```

As you may see, list items separated by *blank line* are parsed differently (wrapped with paragraph).

But `cmark` does not differentiate these cases and parse them into exactly the same tree. That is the main issue I am facing now.

P.S. I do not need to separate them into different lists, I need both items in the same list, but I need to know if they have (or don't have) *blank line* between them in source markdown.

**Comment by ealymbaev** [comment]
Here is an example showing show Github renders these cases.

```
# First Example

- first item
- second item

# Second Example

- first item

- second item
```

renders into:

# First Example

- first item
- second item

# Second Example

- first item

- second item

**Comment by ealymbaev** [comment]
@johnxnguyen actually I am using my own visitor, but it has its own `AttributedStringVisitor` and uses it for handling low-level nodes, like `text`, `emphasis`, `link` and so on. In other words I am using my visitor to form my own blocks, but the text inside blocks are parsed to attributed strings via `AttributedStringVisitor`.

So it would be enough to have this property in `List` node. I am interacting with nodes directly in my custom visitor.

**Comment by ealymbaev** [comment]
I have tested your pull request and it works!

```
Document
    ↳ Heading - L1
        ↳ Text - First Example
    ↳ List - type: Bullet, isTight: true
        ↳ Item
            ↳ Paragraph
                ↳ Text - first item
        ↳ Item
            ↳ Paragraph
                ↳ Text - second item
    ↳ Heading - L1
        ↳ Text - Second Example
    ↳ List - type: Bullet, isTight: false
        ↳ Item
            ↳ Paragraph
                ↳ Text - first item
        ↳ Item
            ↳ Paragraph
                ↳ Text - second item
```

Thanks you for the feature!

**Comment by ealymbaev** [comment]
When are you planning to release new version with this feature?

**Comment by iwasrobbed** [comment]
@ealymbaev I'll release once the PR merges

Also I've given you collaborator access so you can feel free to open PRs and help improve Down in the future

Thanks for raising the issue and digging into the docs
