### ISSUE TITLE
Multiple line break support

### ISSUE THREAD

**Issue by SolorzanoJose** [iwasrobbed/Down#222]
According to https://spec.commonmark.org/dingus/ if I use multiple I `<br/>` should be able to insert multiple line breaks in my text. However, if I parse it using Down the line breaks it just displays `<br/> ` instead of inserting a line break. Any ideas on how to achieve this if there's no planned support in the library?

**Comment by johnxnguyen** [comment]
The attributed string styler unfortunately doesn't support html tags, it simply renders them as code as you have mentioned. Commonmark allows you to force line breaks as shown in [this example](https://spec.commonmark.org/dingus/?text=%0Aone%0A%5C%0A%5C%0A%5C%0A%5C%0A%5C%0Atwo%0A%0A%0A%0A%0Athree%0A). I hope that helps.

**Comment by rob-keepsafe** [comment]
To be clear, `<br/>` is HTML, not CommonMark, so this is not within the scope of what we'd support. Down is simply a library to transform CommonMark into other formats, such as HTML, not the other way around.

**Comment by SolorzanoJose** [comment]
@rob-keepsafe What is the work around available that inspired the workaround available tag? I tried using slashes like in the example by John but Down doesn't support that either.

**Comment by SolorzanoJose** [comment]
I see this being asked over and over in closed tickets but there's no clear answer, if CommonMark supports multi line spaces perhaps we should be open to a PR on this as well?

**Comment by rob-keepsafe** [comment]
@SolorzanoJose As always, this is an open source repo. We welcome any PRs since we don't work on this as our primary job and it's up to the community as a whole to maintain, not just us. Feel free to make improvements if you need it improved, since we don't all have the same use cases.

I would suggest checking that the underlying [cmark](https://github.com/commonmark/cmark) lib behaves correctly first and file an issue there if not since that's what Down is a wrapper for.

**Comment by johnxnguyen** [comment]
@SolorzanoJose when running some tests using the attributed string render (the option that takes a `Styler`) I was able to insert and render multiple line breaks. However keep in mind that if you provide a string literal as input, you need to escape these backslashes with an additional backslash:

```
one
\\
\\
\\
two
```

Hopefully this resolves your issue.
