### ISSUE TITLE
How to pre-calculate height needed for attributed string when using DownLayoutManager

### ISSUE THREAD

**Issue by alexjameslittle** [iwasrobbed/Down#226]
I am embedding a custom label that uses DownLayoutManager inside of a UICollectionViewCell. For the collection view layout I need to precalculate the required height. This is relatively easy using normal NSAttributedString's using a method like this: 
```
func labelSize(for attributedText: NSAttributedString, considering maxWidth: CGFloat) -> CGSize {
    let constraintBox = CGSize(width: maxWidth, height: .greatestFiniteMagnitude)
    let rect = attributedText.boundingRect(with: constraintBox, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil).integral

    return rect.size
}
```

However this doesn't accurately calculate the height when using custom attributes such as the code blocks from this library. 

Could you please help in providing some guidance on how I can calculate the required height for the string based on a max width

**Comment by iwasrobbed-ks** [comment]
Hi there - Unless it is a bug or a feature/API request, please ask general Swift/iOS questions on StackOverflow.com first

If there ends up being Down specific issues, we are happy to take a look

**Comment by alexjameslittle** [comment]
This is down specific, I'm asking how I can calculate the height of the attributed string when it includes code block backgrounds and extra insets that are a part of Down not NSAttributedString

**Comment by johnxnguyen** [comment]
@alexjameslittle so the problem you're having is that the extra insets aren't included in the calculated size? The `DownLayoutManager` contains this info so it would need to be involved in the size calculation. How is your custom label built? Does it use a `DownTextView`?

Would you be able to force the layout manager to lay out the attributed string, then query the size of the text view? Or perhaps you can query the layout manager directly for the size of its content.

**Comment by iwasrobbed-ks** [comment]
Would it not be possible to just use https://developer.apple.com/documentation/uikit/nslayoutmanager/1402980-usedrectfortextcontainer ?
