### ISSUE TITLE
SwiftUI support

### ISSUE THREAD

**Issue by MrWoWander** [iwasrobbed/Down#231]
Hello
Are there any plans to add SwiftUI support soon?

**Comment by iwasrobbed-ks** [comment]
@MrWoWander Please follow the issue / feature request checklists next time since it asks you to search for duplicates before opening a new issue.

See https://github.com/iwasrobbed/Down/issues/199 and feel free to reopen this if you're unable to bridge it into SwiftUI

**Comment by MrWoWander** [comment]
Thanks
I apologize for the inconvenience caused.

**Comment by MrWoWander** [comment]
I offered my example on working with SwiftUI in #260
