### ISSUE TITLE
How to specify font for strong?

### ISSUE THREAD

**Issue by Kalzem** [iwasrobbed/Down#236]
I have a markdown text with only a body which contains strong and italic parts (no headings, no listing, etc).

The default font for the body is a custom font already bold (let's call it "SuperFont-Bold"). How can I specify an even boldier font ("SuperFont-ExtraBold") for the **strong text**?

I cannot find any arguments in the DownStyler/Configuration.

By the way, I'm using `try? down.toAttributedString()` as I need to manipulate and animate letter by letter the final attributed string (so I can't use DownView).

Thanks

**Comment by johnxnguyen** [comment]
Hi @Kalzem , the `AttributedStringVisitor` doesn't use separate fonts for bold and italic, but rather modifies the base font by inserting bold or italic traits. But I think it would be pretty straightforward to achieve what you want to do by subclassing `AttributedStringVisitor` and overriding the `visit` method for strong nodes. You could call the super method first, storing the result in a local variable (of type `NSAttributedString), then modify the attributes of that result, such as changing the font. 

Something like:

```swift
class MyAttributedStringVisitor: AttributedStringVisitor {
  
  override func visit(_ node: Strong) -> NSAttributedString {
    let result = super.visit(node)
    // Modify result...
    return result
  }
  
}

**Comment by iwasrobbed-ks** [comment]
Thanks @johnxnguyen , closing this out but feel free to re-open if needed
