### ISSUE TITLE
Xcode 8.3 warnings

### ISSUE THREAD

**Issue by lucasecf** [iwasrobbed/Down#26]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

It's just me or everyone also have 5 warnings in the new Xcode 8.3? All of them apparently are in the cmark code btw.

![screen shot 2017-04-05 at 14 39 00](https://cloud.githubusercontent.com/assets/1894401/24706003/6d4b3f38-1a0e-11e7-96fd-f103fc9e7692.png)

The first 4 apparently can be fixed by removing this 4 files from the build phase, the other one is a type problem

**Comment by iwasrobbed** [comment]
@lucasecf You can silence these with https://guides.cocoapods.org/syntax/podfile.html#inhibit_all_warnings_bang (or using the `-w` flag if you're not using CocoaPods http://stackoverflow.com/a/8580123/308315)

Xcode 8.3 shows those warnings now for implicit dependencies, but you (typically) shouldn't worry about warnings in pods. The ones shown above can be ignored and have always existed.

**Comment by lucasecf** [comment]
@iwasrobbed I'm already using the flag actually. But it only works for warnings in the code apparently (the last one), so the first 4 ones are always there, unless I remove the files from the build phase in the pod locally, which is not a good alternative, since they will keep coming back after any pod install. I know it's not a big deal, but it's annoying to see warnings there anyways, they are the only ones in our project.

**Comment by iwasrobbed** [comment]
@lucasecf Ah, I see. Unfortunately, some of those files are definitely needed — both from a licensing and functioning perspective — so it's not as easy as just removing them. I'd file a radar w/ Apple and I'll ask around and report back if I hear anything.

**Comment by iwasrobbed** [comment]
@AliSoftware said you could create a copy rule yourself for now, but that seems silly to ask people to do. This feels like Apple went a little too far when they reintroduced those warnings in 3rd party libraries as part of Xcode 8.3.

@lucasecf Best to file a radar so they fix it in one place versus having devs have to fix this for every single 3rd party framework across all projects.

![pasted image at 2017_04_06 20_39](https://cloud.githubusercontent.com/assets/317671/24770981/c6ba129e-1ac0-11e7-9628-3d74be576350.png)

**Comment by lucasecf** [comment]
All right, thanks for the feedback anyways 👍

**Comment by iwasrobbed** [comment]
Seems like the `.inc` and possibly the `.modulemap` files are actually needed during compilation, so it's not enough to just copy them as bundle resources (it will just throw an error).

Therefore, this will need to be fixed via Xcode radar unless someone has an alternative route.

Files in question:

```
- NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/case_fold_switch.inc' of type sourcecode.pascal for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/COPYING' of type text for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/entities.inc' of type sourcecode.pascal for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/module.modulemap' of type sourcecode.module-map for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/case_fold_switch.inc' of type sourcecode.pascal for architecture x86_64
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/COPYING' of type text for architecture x86_64
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/entities.inc' of type sourcecode.pascal for architecture x86_64
    - NOTE  | xcodebuild:  warning: no rule to process file 'Down/Source/cmark/module.modulemap' of type sourcecode.module-map for architecture x86_64
    - WARN  | xcodebuild:  Down/Source/cmark/latex.c:185:18: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
```

Example `.podspec` changes of moving them to bundle resources:

```ruby
Pod::Spec.new do |spec|
  spec.name         = "Down"
  spec.summary      = "Blazing fast Markdown rendering in Swift, built upon cmark."
  spec.version      = "0.3.4"
  spec.homepage     = "https://github.com/iwasrobbed/Down"
  spec.license      = { :type => "MIT", :file => "LICENSE" }
  spec.authors      = { "Rob Phillips" => "rob@desideratalabs.co" }
  spec.source       = { :git => "https://github.com/iwasrobbed/Down.git", :tag => "v" + spec.version.to_s }
  spec.source_files = "Source/{cmark,Enums & Options,Extensions,Renderers}/*.{h,c,swift}", "Source/*.{h,c,swift}"
  spec.ios.source_files = "Source/Views/*.swift"
  spec.osx.source_files = "Source/Views/*.swift"
  spec.public_header_files = "Source/*.h"
  spec.ios.deployment_target = "8.0"
  spec.tvos.deployment_target = "9.0"
  spec.osx.deployment_target = "10.11"
  spec.requires_arc = true
  spec.module_name = "Down"
  spec.preserve_path = 'Source/cmark/module.modulemap'
  spec.pod_target_xcconfig = { 'SWIFT_INCLUDE_PATHS' => '$(SRCROOT)/Down/Source/cmark/**' }
  spec.ios.resources = ['Resources/DownView.bundle', 'Source/cmark/*.inc', 'Source/cmark/COPYING', 'Source/cmark/module.modulemap']
  spec.osx.resources = ['Resources/DownView.bundle', 'Source/cmark/*.inc', 'Source/cmark/COPYING', 'Source/cmark/module.modulemap']
end
```

And resulting error from running `$ pod spec lint Down.podspec --verbose`:

```
The following build commands failed:
	CompileC /Users/rob/Library/Developer/Xcode/DerivedData/App-amlocaltanvvjcfphkngwgkopudx/Build/Intermediates/Pods.build/Release-appletvsimulator/Down.build/Objects-normal/x86_64/houdini_html_u.o Down/Source/cmark/houdini_html_u.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

...

 -> Down (0.3.4)
    - WARN  | xcodebuild:  Down/Source/cmark/latex.c:185:18: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    - ERROR | [tvOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [tvOS] xcodebuild:  Down/Source/cmark/houdini_html_u.c:8:10: fatal error: 'entities.inc' file not found
```

**Comment by iwasrobbed** [comment]
Looks like these are gone in the latest Xcode 9, closing via https://github.com/iwasrobbed/Down/pull/46

**Comment by joshuacleetus** [comment]
still these first 4 warnings appears to me in Xcode 9

**Comment by iwasrobbed** [comment]
Thanks @joshuacleetus I'll leave it open for now. Looks like we're stuck with these warnings. If you wouldn't mind, could you share the rules you're using to silence these so others can use them as well?

**Comment by joshuacleetus** [comment]
Hi @iwasrobbed, I am using the attached rules and it is working for me.
<img width="899" alt="screen shot 2017-10-03 at 12 07 25 pm" src="https://user-images.githubusercontent.com/2602822/31135692-cfba9156-a833-11e7-87cb-ab183404e824.png">

**Comment by 128keaton** [comment]
@joshuacleetus I updated the project settings with those filters--thank you so much!

**Comment by iwasrobbed** [comment]
Closed via #48 ; thanks again @joshuacleetus and @128keaton

**Comment by ladislas** [comment]
for those still having the issue now, activating the new build system fixed it for me.

**Comment by iwasrobbed** [comment]
Fixed and closed "properly" in https://github.com/iwasrobbed/Down/pull/86 ; I'll cut a new pod version tomorrow when I get some time
