### ISSUE TITLE
rendering markdown from file

### ISSUE THREAD

**Issue by atom2ueki** [iwasrobbed/Down#29]
I've tried to render a long markdown format string with `Down`, but it can't be recognised, the only way to do it is rendering one line by one line, like this
```
let inputArray = ["## Hello World", "- list1", "- list2"]
var output: String = ""
        
for input in inputArray {
    let down = Down(markdownString: input)
    // Convert to HTML
    let html = try? down.toHTML()
    output = "\(output)\(html!)"
}
        
self.webview.loadHTMLString(output, baseURL: nil)
```
wondering is there a better way to do it?

**Comment by 128keaton** [comment]
Can you post the actual markdown file?

**Comment by iwasrobbed** [comment]
Closing this as I have not heard back. Feel free to reopen if you're still having the issue.
