### ISSUE TITLE
down.toAttributedString() custom text font and image size

### ISSUE THREAD

**Issue by atom2ueki** [iwasrobbed/Down#33]
due to different size of devices, can't just give a fixed size to image in markdown, is there a way to custom text font and image size after it been converted to `NSAttributedString`, or is there a markdown standard to make this happens?
- markdown sample
```
this is a sample text and image
![](https://s3.atom2ueki.com/images/app_s_3.jpg)
```
- code sample
```
...
let output:NSAttributedString = try! down.toAttributedString()
DispatchQueue.main.async {
    self.uitextview.attributedText = output
}
...
```
thanks!

**Comment by iwasrobbed** [comment]
These questions are specific to styling `NSAttributedString` so you'd have better luck asking someplace like [StackOverflow](https://stackoverflow.com) since Down is only responsible for conversion.

Once it's in one of the many output formats Down supports, they can all be styled differently.
