### ISSUE TITLE
Fenced code syntax highlighting

### ISSUE THREAD

**Issue by kimaldis** [iwasrobbed/Down#35]
Can this be done?

**Comment by iwasrobbed** [comment]
It's just regular markdown so if it can be done in markdown, it can be done.

e.g.

```
func someFunction() {
  // do something
}
```

**Comment by kimaldis** [comment]
But with syntax highlighting on the code?
<img width="646" alt="screen shot 2017-06-24 at 11 09 44" src="https://user-images.githubusercontent.com/4265299/27512085-91a9e4ac-592d-11e7-927f-a497e696751d.png">

**Comment by iwasrobbed** [comment]
Yes, there is an example in the readme: https://github.com/iwasrobbed/Down#view-rendering
