### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by neoneye** [iwasrobbed/Down#37]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

1. I downloaded a zip with the project.
2. I tried to run the project in Xcode.
3. I realized that there was only unittests.

## What did you expect to happen?

I'm usually looking for an Example project that shows how it looks on iOS or on macOS.

## What happened instead?

There was no Example project, so I created this issue.

**Comment by iwasrobbed** [comment]
Hi @neoneye 👋 

I'm happy to incorporate one with a pull request, but the readme gives examples of all usage and there is even a [DownView](https://github.com/iwasrobbed/Down#view-rendering) component to make things very simple.

**Comment by 128keaton** [comment]
Yes it’s extremely basic–I added an example anyway.

**Comment by iwasrobbed** [comment]
Thanks @128keaton
