### ISSUE TITLE
Unable to build with Xcode 9

### ISSUE THREAD

**Issue by ahwulf** [iwasrobbed/Down#41]
# Report

## What did you do?

Building my OS X project with Down under Xcode 9 Beta 6 failed due to framework built with previous version of swift error. I then changed my local Down to be swift 4, updated the source, ran the few tests. Removed the existing Down framework and added the newly built one.

## What did you expect to happen?

That my project would build.

## What happened instead?

It still complains that the framework is built with an older version of Swift. I ensured the only copy is the one I built. Is there anything odd about the Down build settings?

**Comment by ahwulf** [comment]
Ugh stupid xcode beta issues.

**Comment by iwasrobbed** [comment]
Thanks @ahwulf we'll have a look at Swift 4 changes soon.

**Comment by 128keaton** [comment]
Make sure you set your Xcode build tools to the beta when using a dependency manager, e.g.
`sudo xcode-select -s /Applications/Xcode-beta.app`
