### ISSUE TITLE
Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by nitesh-iosdev** [iwasrobbed/Down#42]
Seeing error:

>MyProject/Pods/Down/Source/Views/DownView.swift:9:8: Module file was created by an older version of the compiler; rebuild 'WebKit' and try again: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/arm64/WebKit.swiftmodule

**Comment by iwasrobbed** [comment]
@nitesh-iosdev Are you using a beta version of Xcode? This hasn't been converted to Swift 4 / Xcode beta yet

**Comment by iwasrobbed** [comment]
Please try using this branch https://github.com/iwasrobbed/Down/tree/swift4 and let me know if you have any issues.

**Comment by nitesh-iosdev** [comment]
I was using xcode8.2.1, I just updated xcode8.3.3 and this issue is resolved.
