### ISSUE TITLE
Carthage install fails: no such module 'libcmark'

### ISSUE THREAD

**Issue by tebs1200** [iwasrobbed/Down#43]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Added Down to my `Cartfile` and ran `carthage update --platform iOS`. I'm using the latest version of Carthage (0.25.0). Xcode version 8.3.3

## What did you expect to happen?

I expected the installation to complete successfully

## What happened instead?

The carthage update failed when it got to Down:

    Build Failed
        Task failed with exit code 65:

I checked the build logs, and noticed the error:

    error: no such module 'libcmark'

**Comment by iwasrobbed** [comment]
I unfortunately do not use Carthage, but it sounds like it's not embedding the framework into the project correctly. You may want to manually check the which frameworks are embedded in your target in either of the General or Build Phases tabs.

**Comment by tebs1200** [comment]
Having a quick look at [this article](https://medium.com/@filippotosetto/how-to-create-a-carthage-framework-8d9d65f98ac2), it may be that a cart file is needed in the project for any dependencies.

**Comment by tebs1200** [comment]
I've forked the project and will see if I can get it to work with Carthage.

**Comment by 128keaton** [comment]
interesting--when I get time (assignments ugh) I'll take a look.

**Comment by 128keaton** [comment]
This should be fixed in the latest PR. Give it a try.

**Comment by iwasrobbed** [comment]
Closing for now, feel free to re-open if it's still broken for you @tebs1200

**Comment by davegomez** [comment]
I'm getting the same error when trying to build the example project using Xcode 9 `Missing required module 'libcmark'` and that's the only information I got from Xcode.

**Comment by shannonchou** [comment]
same error as @davegomez

**Comment by iwasrobbed** [comment]
@davegomez / @shannonchou Your issue w/ the example app is different than this parent issue. See https://github.com/iwasrobbed/Down/pull/58

**Comment by Cooper-Han** [comment]
The same problem occurred in Xcode 26.

**Comment by angu-software** [comment]
Issue is happening for me in Xcode 26 RC with Down 0.11.0 and integrated with Cocoapods!

Edit: Found a way to get passt the issue by disabling `Explicit Build Mode` in my Xcode project

Also See: https://forums.swift.org/t/xcode-26-unable-to-find-module-dependency/80516
