### ISSUE TITLE
Building for tvOS fails

### ISSUE THREAD

**Issue by 128keaton** [iwasrobbed/Down#49]
tvOS doesn't have a WebKit framework, so creating a separate target might be needed.
![screen shot 2017-10-04 at 1 17 15 pm](https://user-images.githubusercontent.com/1402918/31192251-5ff1249c-a906-11e7-871a-ca7e21a782f4.png)

**Comment by alfredctchoi** [comment]
Getting a similar issue when running `carthage update`.  In the error logs, I get 
```
~project/Carthage/Checkouts/Down/Source/Views/DownView.swift:9:8: error: no such module 'WebKit'
import WebKit
       ^
```

**Comment by 128keaton** [comment]
@alfredctchoi you will need to state the platform when running update

**Comment by iwasrobbed** [comment]
Sorry for the slow response; the easiest thing to do might be to just conditionally compile using `#if os(tvOS)`

I'll push a change with this soon to make `DownView` unavailable for tvOS.
