### ISSUE TITLE
Push v0.4.1 to cocoapods 

### ISSUE THREAD

**Issue by wattson12** [iwasrobbed/Down#51]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I tried to install `0.4.1` via cocoapods 

## What did you expect to happen?

I expected that cocoapods would be aware of `0.4.1`

## What happened instead?

No such version could be found, latest cocoapods version is `0.3.4`. I was able to install by pointing to the `v0.4.1` tag

It would be great to get the new version pushed to cocoapods so i can reference by version

**Comment by iwasrobbed** [comment]
Looks like CocoaPods is having an issue building it from a `pod lib lint` even though it installs fine otherwise.

You're welcome to look into it, but unfortunately I don't have much free time at the moment since I'll be moving soon.

As you noted, you can just point to the github tag instead and it'll install `0.4.1` from it:
>pod 'Down', :git => 'https://github.com/iwasrobbed/Down/Down.git', :tag => '0.4.1'

---

Some breadcrumbs for whoever wants to have a look:

```shell
$ pod lib lint --verbose --no-clean --allow-warnings

...

 -> Down (0.4.1)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/case_fold_switch.inc' of type sourcecode.pascal for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/COPYING' of type text for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/entities.inc' of type sourcecode.pascal for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/module.modulemap' of type sourcecode.module-map for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/case_fold_switch.inc' of type sourcecode.pascal for architecture x86_64
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/COPYING' of type text for architecture x86_64
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/entities.inc' of type sourcecode.pascal for architecture x86_64
    - NOTE  | xcodebuild:  warning: no rule to process file '/Users/rob/Down/Source/cmark/module.modulemap' of type sourcecode.module-map for architecture x86_64
    - ERROR | xcodebuild:  /Users/rob/Down/Source/Renderers/DownASTRenderable.swift:10:8: error: no such module 'libcmark'
```

I ran into this in the past (https://github.com/CocoaPods/CocoaPods/issues/5442) but not sure what's changed that broke it again.

**Comment by iwasrobbed** [comment]
Actually, it seems like just `pod lib lint` didn't work but the `pod trunk push` worked fine 

Looks like `pod spec lint` is a better option since it checks out the remote instead of trying to use local files where `SWIFT_INCLUDE_PATHS` breaks

```
 🎉  Congrats

 🚀  Down (0.4.1) successfully published
 📅  October 21st, 06:37
 🌎  https://cocoapods.org/pods/Down
 👍  Tell your friends!
```

**Comment by wattson12** [comment]
Awesome, thanks 👍
