### ISSUE TITLE
Syntax highlighting themes

### ISSUE THREAD

**Issue by alexrabin** [iwasrobbed/Down#59]
This is a feature request. 
Can you guys create any more themes. 
It would be nice to Choose from a light or a dark theme for syntax highlighting

**Comment by iwasrobbed** [comment]
Hi @alexrabin 👋 

Down is structured such that you can just add your own bundle (w/ css, js, etc) for whatever you'd like to customize in the `DownView` class. There are just too many unique customizations to consider, so we'd rather leave it up to the end user to modify to their heart's content.

See this test for an example: https://github.com/iwasrobbed/Down/blob/master/Tests/DownViewTests.swift#L71

Related: https://github.com/iwasrobbed/Down/pull/27 and https://github.com/iwasrobbed/Down/issues/15

**Comment by alexrabin** [comment]
@iwasrobbed okay that’s fair
