### ISSUE TITLE
Installation via Swift Package Manager

### ISSUE THREAD

**Issue by tp** [iwasrobbed/Down#61]
Hi,

I wanted to try out this package (as it seems to be the only Swift package to provide access to a Markdown AST for custom transforms), but hadn't yet set up CocoaPods or Carthage on my sample CLI application.

I was wondering whether there was anything preventing this project to provide a `Package.swift` configuration to be installable via SPM and if not whether you have any objections to providing that option.

Thanks!

**Comment by iwasrobbed** [comment]
Hi @tp 👋 

We're happy to accept a pull request with that functionality added, but we don't have any plans to introduce it ourselves at this time.

**Comment by iwasrobbed** [comment]
Going to close this out since it's been 6 months. As always, I welcome pull requests from the broad community using this if it's an important need.

**Comment by iwasrobbed** [comment]
FYI, this is being done in https://github.com/iwasrobbed/Down/pull/150
