### ISSUE TITLE
Some warnings to fix

### ISSUE THREAD

**Issue by anelad** [iwasrobbed/Down#64]
* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Just installed via CocoaPods.

## What did you expect to happen?

No warnings or errors.

## What happened instead?

1. Don't know how but there are 4 non-compilable sources in the Compile Sources list. I forked the Down project and see that there are not in the Compile Sources list. Odd. 

   - case_fold_switch.inc
   - COPYING
   - entities.inc
   - module.modulemap

2. `latex.c` line 185: `realurllen = url_len;` gives warning:
`Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int'`

   A type casting solves the issue.
   `realurllen = (int) url_len;`

P.S: Thank you for this great spec! It saved a life!

**Comment by iwasrobbed** [comment]
Hi @anelad 👋 Does this help address your issue? https://github.com/iwasrobbed/Down/issues/26

**Comment by anelad** [comment]
Hi @iwasrobbed. Don’t know how I couldn’t see that. Sorry & thank you.
