### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by anelad** [iwasrobbed/Down#65]
* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

I have to cache the images in the markdown for offline usage. Is there any way to achieve this?

**Comment by iwasrobbed** [comment]
To better help me understand, how are you downloading the source file and then rendering the markdown into a view?

**Comment by anelad** [comment]
in my case, markdowns are string objects stored in Firebase Cloud Firestore. I want to use Firebase Cloud storage references for image links. But for now using https links.

When I parse markdown into NSAttribıted string and show it in UITextView, the image is cached. But I have no idea how and where it is cached.

**Comment by iwasrobbed** [comment]
This falls a bit outside of Down's responsibilities since it's just a text transformation library. It's up to clients to handle rendering and caching concerns
