### ISSUE TITLE
iOS8 crash

### ISSUE THREAD

**Issue by hotchner** [iwasrobbed/Down#66]
env: XCode9/swift4
crashed on ios8/iphone6
dyld: Symbol not found: _NSCharacterEncodingDocumentOption

**Comment by iDevPro** [comment]
replace init in NSAttributedString+HTML.swift and try again :)

 convenience init(htmlString: String) throws {
        guard let data = htmlString.data(using: String.Encoding.utf8) else {
            throw DownErrors.htmlDataConversionError
        }

        try self.init(data: data, options: [NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType, NSCharacterEncodingDocumentAttribute: String.Encoding.utf8.rawValue] , documentAttributes: nil)
    }

**Comment by iwasrobbed** [comment]
Thanks @iDevPro 

Just a note: We'll be formally removing iOS 8 support from upcoming releases (as iOS 11 adoption is pretty high), so please fork this library if you still need to support it.
