### ISSUE TITLE
get heigth when add downview to other view?

### ISSUE THREAD

**Issue by hotchner** [iwasrobbed/Down#67]
i tried to get height in WKWebview's delegate: didFinish Navigation, but get the wrong height, much heigher than correct.
How can i get then corret DownView height?

**Comment by 128keaton** [comment]
You might want to get the content size instead, since the WKWebView's height is the size of the actual view--the content size should extend beyond that. Read: https://stackoverflow.com/questions/16910117/how-to-find-the-height-of-content-of-scroll-view-or-webview-in-iphone

**Comment by hotchner** [comment]
i tried two methods to get height, all fialed.
1.  js: document.body.offsetHeight
2. webView.scrollView.contentSize.height

**Comment by iwasrobbed** [comment]
@hotchner Can you please explain what you're trying to do with the height? 

There are different heights, so it's difficult to point you in the right direction unless we understand your use case.

**Comment by hotchner** [comment]
@iwasrobbed  I add down to a tableViewCell, and i need to update tableView height when downView complete render. So i calculated the height in webView's delegate, didFinish Navigation.

**Comment by iwasrobbed** [comment]
You're better off asking that on StackOverflow (e.g. https://stackoverflow.com/questions/27515236/how-to-determine-the-content-size-of-a-wkwebview?noredirect=1&lq=1). 

`DownView` is nothing more than a basic `WKWebView` subclass so we'd rather avoid general programming questions unless it's specifically related to the `Down` lib and reproducible for us to debug.
