### ISSUE TITLE
Installing with Carthage for Mac fails

### ISSUE THREAD

**Issue by georgemp** [iwasrobbed/Down#70]
Please help prevent duplicate issues before submitting a new one:

* [Y ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report
I tried installing Down using Carthage 0.28.0. However, it errors out with the following

``
Failed to write to /Users/georgemp/TestProject/Carthage/Build/Mac/Down.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Down.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/georgemp/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/Down/v0.4.2/Build/Intermediates.noindex/ArchiveIntermediates/Down/BuildProductsPath/Release-iphoneos/Down.framework, NSFilePath=/Users/georgemp/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/Down/v0.4.2/Build/Intermediates.noindex/ArchiveIntermediates/Down/BuildProductsPath/Release-iphoneos/Down.framework, NSUnderlyingError=0x7fd250923f10 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
``

## What did you do?

Tried installing Down with the following commands

`carthage update Down --platform Mac` 

`carthage update Down --platform Mac --no-use-binaries`

## What did you expect to happen?

Expected to get a built Down.framework in Carthage/Build/Mac

## What happened instead?

The build errored with the error message pasted in the report section

**Comment by kengruven** [comment]
It appears that the changeset that broke Mac builds was f2169a1f, part of #28.

For anyone else (like me) who doesn't need the newer features, `github "iwasrobbed/Down" == 0.3.3` works fine.

**Comment by tonyarnold** [comment]
Huh, this is a bit special - the framework is built and archived successfully, but Carthage is looking in `BuildProductsPath/Release-iphoneos` rather than `BuildProductsPath/Release`. I'll try to have a look at it today.

**Comment by georgemp** [comment]
Unfortunately, I'm still getting the same error when installing via carthage. I also tried deleting my carthage cache, and, trying to install again. My Carthage version is 0.28.0 and XCode is at version 9.2

My workaround now is to add Down.xcodeproj to my application, and, use the built library. 

If there is anything I can do to help test/debug this, do let me know. Thanks

**Comment by tonyarnold** [comment]
@georgemp how are you specifying the dependency in your Cartfile? This hasn't been released in a tagged version yet, so you would need to do:

```ruby
github "iwasrobbed/Down" "master"
```

**Comment by georgemp** [comment]
Aah..perfect. That worked :)

**Comment by iwasrobbed** [comment]
Just tagged this release v0.5.0 @georgemp and thanks again @tonyarnold 🙌
