### ISSUE TITLE
WatchKit Support

### ISSUE THREAD

**Issue by WillBishop** [iwasrobbed/Down#71]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

I'd like WatchKit support for Down.

## What did you do?

I tried manually adding the Framework, however, this caused too many issues.

## What did you expect to happen?

I didn't expect it to work, but I would like it to

## What happened instead?

It didn't work

**Comment by iwasrobbed** [comment]
I'm happy to accept any pull requests for this, but as I don't have a need for it myself it is pretty low priority amongst my projects at this time.

**Comment by WillBishop** [comment]
Alright, It's definitely out of my capabilities at the moment. The reason I asked is I'm developing a Reddit client for the Apple Watch, and Markdown -> NSAttributedText would be amazing

**Comment by iwasrobbed** [comment]
Going to close this out since it's been 5 months. As always, I welcome pull requests from the broad community using this if it's an important need.
