### ISSUE TITLE
macOS 10.11 support?

### ISSUE THREAD

**Issue by kengruven** [iwasrobbed/Down#73]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

- I built Down.framework for macOS, using Carthage.
- Then I dragged the framework to my Mac application (which is built for 10.11).

## What did you expect to happen?

The application would (still) build.

## What happened instead?

Xcode refused to build the application, because Down.framework has `MACOSX_DEPLOYMENT_TARGET = 10.12`.

Down doesn't use any 10.12 APIs, though, so there doesn't appear to be any downside to changing it to `MACOSX_DEPLOYMENT_TARGET = 10.11`.

An older macOS target isn't out of line with the other supported platforms.  Down.framework still claims to support iOS 8, for example, which is roughly the age of macOS 10.10.

**Comment by iwasrobbed** [comment]
Happy to accept a pull request for this and other tickets (I don't personally use Down with macOS)
