### ISSUE TITLE
Swift 3+ convention for capitalization

### ISSUE THREAD

**Issue by kengruven** [iwasrobbed/Down#74]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

When using Down, all of the non-type identifiers (funcs, vars, etc.) follow the Swift 3+ convention of starting with a lower-case letter, except in the case of `struct DownOptions`.  It still uses the Swift 2 convention of UpperCase identifiers:

    public static let SourcePos = DownOptions(rawValue: CMARK_OPT_SOURCEPOS)

## What did you expect to happen?

I think Down should use the newer convention and call these symbols `sourcePos`, `hardBreaks`, etc.

## What happened instead?

Down still uses the Swift 1/2 convention here: `SourcePos`, `HardBreaks`, etc.

This is a change to the public interface, but the project version number is still 0.x, so according to semver, breaking changes are allowed.  Alternatively, it could define both capitalizations in the struct (like `SourcePos` and `sourcePos`), to allow users time to update their code.

**Comment by iwasrobbed** [comment]
👍 Happy to accept a PR for this breaking change and we'll just bump the version like you suggested
