### ISSUE TITLE
Add support for Carthage

### ISSUE THREAD

**Issue by codeslubber** [iwasrobbed/Down#8]

**Comment by mbuchetics** [comment]
seems to be working just fine with Carthage

**Comment by iwasrobbed** [comment]
@mbuchetics Thanks! Mind giving an example on how they can integrate it and I'd be happy to add it to the readme?

**Comment by mbuchetics** [comment]
I simply added 
`github "iwasrobbed/Down" ~> 0.3`
to my `Cartfile` and ran `carthage update` (see https://github.com/Carthage/Carthage).

You can omit the version and just put
`github "iwasrobbed/Down"`
This is how most frameworks are describing it in their readme (however, I think it is good practice to specify a version).

Other than that you just have to make sure that your Xcode schemes are shared (https://github.com/Carthage/Carthage#share-your-xcode-schemes). But you are already doing that, so it just works out of the box 👍

**Comment by iwasrobbed** [comment]
Thanks @mbuchetics !! I will add this today
