### ISSUE TITLE
`DocumentReadingOptionKey` Error via pod

### ISSUE THREAD

**Issue by sarankumar291** [iwasrobbed/Down#80]
Please help prevent duplicate issues before submitting a new one:

* [ ] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with what happened instead (e.g. the issue).  

While installing pod file getting error "**DocumentReadingOptionKey** is unavailable in Swift"

**Comment by krummler** [comment]
Hi there, this seems to be the same issue as:

https://github.com/iwasrobbed/Down/issues/63

I'm having the same problem

**Comment by iwasrobbed** [comment]
Hi there 👋 Can you please provide a bit more information. E.g. what version of Swift? what version of Xcode? Can you reproduce this in a minimal project (i.e. create a new project and only install the `Down` pod)

I'm afraid I can't do much unless you give more hints or help pinpoint it.

**Comment by iwasrobbed** [comment]
Just an fyi: I tried reproducing this in a clean project on Xcode 9 and Xcode 9.2 using Swift 4 and cannot repro. 

```ruby
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# use frameworks for Swift
use_frameworks!

project 'Down-Integration'

target 'Down-Integration' do
  pod 'Down'
end
```

<img width="722" alt="screen shot 2018-02-28 at 9 43 15 am" src="https://user-images.githubusercontent.com/317671/36797390-d41d81ac-1c75-11e8-81af-8f361e13244c.png">

<img width="762" alt="screen shot 2018-02-28 at 9 43 50 am" src="https://user-images.githubusercontent.com/317671/36797395-d70be48a-1c75-11e8-9188-0adcba6ba20f.png">

**Comment by krummler** [comment]
For me this happened during pod install, but while trying to build the app.

It ended up being because my project was still swift 3.2, while Down is expecting Swift 4? 

I think you can get around by downgrading down (0.3.3), migrating to swift 4, then updating to down 0.5.0 again.

**Comment by iwasrobbed** [comment]
@krummler Yes, Down is written in Swift 4 but should be capable of being used in Swift 3 projects as long as the versions are set correctly. What version of Xcode are you using?

Examples [here](https://www.cerebralgardens.com/blog/entry/2017/10/04/mix-and-match-swift-3-swift-4-libraries-with-cocoapods) and [here](https://stackoverflow.com/questions/46101625/using-cocoapods-mixed-swift3-and-swift4-pods)

**Comment by sarankumar291** [comment]
After changed to swift Version 3.2 to 4 it started working Thanks

**Comment by idsky2** [comment]
I'm getting this now, with XCode 9.4.1, Swift 4.1 and any iOS target (just tried 11.4)
Apple says DocumentReadingOptionKey is only iOS11+ but Down is meant to work on iOS9+
