### ISSUE TITLE
Converting \n in paragraphs into <br>, while marking down an html

### ISSUE THREAD

**Issue by joshuacleetus** [iwasrobbed/Down#83]
How can i convert `\n` in paragraphs into `<br>`? 
In other words, is there any options that can make markdown newline (`\n`) between paragraphs to line break?

For example if the markdown looks like below:
```
Hi,<br>\n\ndadsaadsdsada<br>\n\n1\\. dsadsad\n2\\. ea2eqwewqewq\n3\\. dewacxzcxczxcxczc\n4\\. dasfdfdsfdfsdfsfs
```

How to show the output like 

```Hi,

dadsaadsdsada

1. dsadsad
2. ea2eqwewqewq
3. dewacxzcxczxcxczc
4. dasfdfdsfdfsdfsfs```

**Comment by iwasrobbed** [comment]
CommonMark doesn't care about newlines ([test it here](http://spec.commonmark.org/dingus), so you could have 30 newlines between paragraphs and it'd only render one line break.

I'd just manually replace `\n`, `\r`, etc with `<br/>` in your strings before rendering.

**Comment by SolorzanoJose** [comment]
@iwasrobbed if I replace \n with <br/> the parser eats it and it doesn't show up in the styler. I'm trying to add multiple line breaks in my text.

**Comment by johnxnguyen** [comment]
@SolorzanoJose  You can force line breaks as shown in [this example](https://spec.commonmark.org/dingus/?text=%0Aone%0A%5C%0A%5C%0A%5C%0A%5C%0A%5C%0Atwo%0A%0A%0A%0A%0Athree%0A).
