### ISSUE TITLE
Image size NSAttributedString

### ISSUE THREAD

**Issue by arguiot** [iwasrobbed/Down#89]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report
I have an image in my markdown content, but when I render it with Down, it is way bigger than expected

## What did you do?

I opened this issue

## What did you expect to happen?

I expected the image to fit the width of the NSAttributedString view.

## What happened instead?

The image was too big.

**Comment by iwasrobbed** [comment]
Down is just a Markdown transformer. It's up to you to style the output based on the device and your design spec. See https://stackoverflow.com/a/33961204/308315 for more info.
