### ISSUE TITLE
Support for Dynamic Type

### ISSUE THREAD

**Issue by deeje** [iwasrobbed/Down#90]
# Report

## What did you do?

change the current Text Size (either in Settings > Display & Brightness > Text Size, or in Control Center)

## What did you expect to happen?

the size of text in DownView should change appropriately

## What happened instead?

the size of text doesn't change relative to the Dynamic Type text size setting

**Comment by iwasrobbed** [comment]
In the spirit of open source code, I'm happy to accept a pull request for this ([especially since it's an easy change](http://www.interactiveaccessibility.com/blog/text-resizing-web-pages-ios-using-dynamic-type)). Thanks!

**Comment by Fenrikur** [comment]
Dynamic Type can already be used with Down e.g. by supplying a `Down.toAttributedString(options: DownOptions, stylesheet: String?)` with an appropriate stylesheet. The main issue here is that by setting the `font` attribute on all HTML elements, you will automatically strip clear any other changes to their style made via `font-*` attributes like `font-weight` or `font-size`, which results in `<strong>` and other elements that by default affect `font-*` attributes being rendered like any other unstyled part of the input.
While you can therefore easily support Dynamic Type by supplying `* { font: -apple-system-body; }` for the `stylesheet` parameter, you would need to apply additional styles (e.g. `h1, h2, h3, h4, h5, h6, strong { font-weight: bold; } em { font-style: italic; } h1 { font-size: 175%; } h2 { font-size: 150%; } h3 { font-size: 130%; } h4 { font-size: 115%; } h5 { font-style: italic; }`) alongside that rule to retain styling for headings etc.

**Comment by iwasrobbed** [comment]
It looks like a workaround has been provided, so I'm going to close this issue. I'm also open to accepting a pull request in the future to add support 👍 

See workarounds:

- https://github.com/iainsmith/ios/commit/2ad2ba9a1ca01480b1538e7bfa2ae6af201cd5cf
- https://github.com/iwasrobbed/Down/issues/90#issuecomment-411877259

**Comment by iwasrobbed** [comment]
FYI: this is now possible via the default `Styler` via https://github.com/iwasrobbed/Down/pull/177
