### ISSUE TITLE
[Xcode 10] Crash in XCBuildService; need to use old build system

### ISSUE THREAD

**Issue by remaerd** [iwasrobbed/Down#91]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

ℹ I downloaded and open Down repository with Xcode 10.

## What did you expect to happen?

ℹ It can build

## What happened instead?

ℹ XCBuildService crashed. So I can't build the framework.

**Comment by MrAlek** [comment]
Using the legacy build system instead of the new one fixes the issue. In Xcode: `File -> Project Settings -> Build System -> Legacy Build System`
