### ISSUE TITLE
[iOS 10+] Warnings for WebKit signal service and latex.c

### ISSUE THREAD

**Issue by antonjazz** [iwasrobbed/Down#94]
* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I've been using Down successfully in an iOS app project (Xcode 9.4.1, build for iOS 10.0+)

## What happened?

It runs fine for me (except for issue #93) but receive two unexpected warnings:

- at build-time latex.c line 185 generates this warning:  
  `Implicit conversion loses integer precision: ‘size_t’(aka 'unsigned long' to ‘int’`

- at runtime, the app generates the following output several times
  `Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`
  `Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service`
  Down is the only part of my app that is using WebKit, so it must be related to Down.

Any suggestions?

**Comment by iwasrobbed** [comment]
As always, I'm happy to accept pull requests from the community. It's always nice to have help when I've already spent a lot of time building this for others ;) 

Here's a few clues for you: http://lmgtfy.com/?q=site%3Astackoverflow.com+Could+not+signal+service+com.apple.WebKit.WebContent

I'll be traveling for a while and won't have time to investigate

**Comment by iwasrobbed** [comment]
As for `Implicit conversion loses integer precision: ‘size_t’(aka 'unsigned long' to ‘int’`, it depends on how you're integrating the library. CocoaPods should silence these sorts of warnings since it's within the underlying C library rather than the Swift wrapper

**Comment by antonjazz** [comment]
Thanks, Rob. I am indeed using CocoaPods to integrate Down, so I'm not sure why I'm getting the implicit conversion warnings… but I'll ignore them until there's a reason why I can't.

**Comment by phoney** [comment]
The loses precision warning is a legitimate warning. I'm sure the code runs fine but there's a type mismatch. Fixing it would be a simple typecast or changing the type of one of the variables. @iwasrobbed  is that a change that you'd accept in a PR?

**Comment by iwasrobbed** [comment]
Going to close this as @phoney updated cmark to v0.28.3 which would fix that warning.

For the WebKit warning, please ensure you're adding `DownView` to the parent view before loading a markdown string into it (i.e. https://stackoverflow.com/a/44623268/308315)
