### ISSUE TITLE
&rdquo; not being rendered

### ISSUE THREAD

**Issue by ericmarkmartin** [iwasrobbed/Down#95]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Rendered a `DownView` with a markdown string

## What did you expect to happen?

I `&rdquo;` to turn into a right quotation mark

## What happened instead?

the text `&rdquo;` (without the quotes) appeared instead.

**Comment by ericmarkmartin** [comment]
With all due respect, I'm not sure how this is an enhancement and not a bug.

**Comment by iwasrobbed** [comment]
@ericmarkmartin Thanks Eric. Closing this one as it's duplicated by #99 which has more information
