### ISSUE TITLE
Back Gesture

### ISSUE THREAD

**Issue by DmitriyTerekhin** [iwasrobbed/Down#96]
Hello! 
I want to use gesture for return back to previous view controller. I added back gesture to my view controller that has downView (i just did some setups for navigation controller). But the downView overlap my ViewController's view and don't allow to use that gesture. How to use back gesture with downView???

**Comment by 128keaton** [comment]
DownView inherits from WKWebView. 

https://www.hackingwithswift.com/example-code/wkwebview/how-to-enable-back-and-forward-swiping-gestures-in-wkwebview

**Comment by iwasrobbed** [comment]
As Keaton said, there are multiple ways to enable back gestures. If you're composing your own view hierarchy with a `DownView` inside of a view controller which is inside of a navigation controller, you'll like want to enable the `navigationController.interactivePopGestureRecognizer` like is described here: https://stackoverflow.com/a/43433530/308315

This isn't a Down specific question, so I'm closing this.
