### ISSUE TITLE
Is there a way to convert NSAttributedString back to markdown?

### ISSUE THREAD

**Issue by hyouuu** [iwasrobbed/Down#98]
Please help prevent duplicate issues before submitting a new one:

* [v] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

Is there a way in Down to do that? If not, any recommended approaches? Sorry if it's a dumb question

**Comment by iwasrobbed** [comment]
You can convert it to HTML and then convert that to Markdown. Both of those are unfortunately outside the scope of this library.

E.g. https://stackoverflow.com/questions/5298188/how-do-i-convert-nsattributedstring-into-html-string

**Comment by hyouuu** [comment]
Thanks for the quick reply and pointer!
